// testId = 1 -> A variant savollari
const TEST_ID_A = 1;

export const questionsA = [
  // ════════════════════════════════════════
  // GRAMMAR  (1 - 50)
  // ════════════════════════════════════════

  // 1
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "___ Shingo speak English very well?",
    options: JSON.stringify(["Has", "Can", "Is", "Do"]),
    correctAnswer: "Can",
    explanation: "Qobiliyat haqida so'ralganda 'Can' ishlatiladi.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 2
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Maura and Carl ___ got a birthday present for Adriano.",
    options: JSON.stringify(["have", "has", "are", "is"]),
    correctAnswer: "have",
    explanation: "Ko'plik ega bilan 'have got' ishlatiladi.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 3
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "There ___ a new Italian restaurant in town.",
    options: JSON.stringify(["are", "has", "have", "is"]),
    correctAnswer: "is",
    explanation: "'A new restaurant' birlik, shuning uchun 'There is'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 4
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Yvette ___ on Saturdays.",
    options: JSON.stringify(["study", "does study", "studies", "studys"]),
    correctAnswer: "studies",
    explanation: "3-shaxs birlikda Present Simple fe'liga -s qo'shiladi: 'studies'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 5
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Arturo's dad ___ dinner now.",
    options: JSON.stringify(["don't cook", "aren't cooking", "doesn't cook", "isn't cooking"]),
    correctAnswer: "isn't cooking",
    explanation: "'Now' hozirgi davom zamoni: 'isn't cooking'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 6
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Fadi is sixteen. Risa is fourteen. Fadi is ___ than Risa.",
    options: JSON.stringify(["old", "oldest", "more old", "older"]),
    correctAnswer: "older",
    explanation: "Ikki odamni solishtirish uchun qiyosiy daraja: 'older'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 7
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "___ there a match yesterday?",
    options: JSON.stringify(["Were", "Was", "Is", "Are"]),
    correctAnswer: "Was",
    explanation: "'A match' birlik va o'tgan zamon: 'Was there...?'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 8
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Milo ___ a gold medal last week!",
    options: JSON.stringify(["won", "wined", "winning", "win"]),
    correctAnswer: "won",
    explanation: "'Win' fe'lining o'tgan zamoni - 'won'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 9
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Did they ___ Cecil this morning?",
    options: JSON.stringify(["saw", "seeing", "see", "sawed"]),
    correctAnswer: "see",
    explanation: "'Did' bilan asosiy fe'l boshlang'ich shaklda keladi: 'see'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 10
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Don't take my smartphone. You ___ take my things!",
    options: JSON.stringify(["have to", "mustn't", "has to", "don't have to"]),
    correctAnswer: "mustn't",
    explanation: "Taqiqni bildirish uchun 'mustn't' ishlatiladi.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 11
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "There was a notebook in the bag. ___ notebook was blue.",
    options: JSON.stringify(["The", "A", "There", "An"]),
    correctAnswer: "The",
    explanation: "Oldin aytilgan narsa haqida gapirilganda 'The' ishlatiladi.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 12
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Marina ___ on holiday next week.",
    options: JSON.stringify(["going", "go", "goes", "is going"]),
    correctAnswer: "is going",
    explanation: "Kelajakdagi reja uchun Present Continuous: 'is going'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 13
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "We ___ TV every afternoon.",
    options: JSON.stringify(["doesn't watch", "aren't watching", "don't watch", "don't watching"]),
    correctAnswer: "don't watch",
    explanation: "'We' bilan Present Simple inkori: 'don't watch'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 14
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Where ___ live?",
    options: JSON.stringify(["is your aunt", "does your aunt", "do your aunt", "your aunt does"]),
    correctAnswer: "does your aunt",
    explanation: "3-shaxs birlik savolda yordamchi fe'l 'does' keladi.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 15
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Hi, Vanessa. What ___?",
    options: JSON.stringify(["do you do", "are you doing", "are you do", "you do"]),
    correctAnswer: "are you doing",
    explanation: "Hozir nima qilayotganini so'rash: 'What are you doing?'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 16
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Bernie and Carlos usually walk to school, but this week they ___ the bus.",
    options: JSON.stringify(["are taking", "take", "taking", "is taking"]),
    correctAnswer: "are taking",
    explanation: "'This week' vaqtinchalik holat, Present Continuous: 'are taking'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 17
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "There ___ a concert at our school last night.",
    options: JSON.stringify(["were", "is", "had", "was"]),
    correctAnswer: "was",
    explanation: "'A concert' birlik va o'tgan zamon: 'was'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 18
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Sergey ___ at home yesterday.",
    options: JSON.stringify(["doesn't stay", "don't stayed", "didn't stay", "didn't stayed"]),
    correctAnswer: "didn't stay",
    explanation: "O'tgan zamon inkorida 'didn't + verb' ishlatiladi.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 19
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Sunita ___ this online game when she was little.",
    options: JSON.stringify(["use to play", "used to play", "used play", "used to playing"]),
    correctAnswer: "used to play",
    explanation: "O'tmishdagi odat uchun 'used to + verb' ishlatiladi.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 20
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "___ have a smartwatch five years ago?",
    options: JSON.stringify(["Did you used to", "Do you use to", "Do you used", "Did you use to"]),
    correctAnswer: "Did you use to",
    explanation: "Savolda 'Did you use to...?' shakli to'g'ri.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 21
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Peng keeps ___ us!",
    options: JSON.stringify(["texting", "text", "to text", "texts"]),
    correctAnswer: "texting",
    explanation: "'Keep' dan keyin gerund (-ing) keladi.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 22
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Rafael needs ___ his phone.",
    options: JSON.stringify(["charge", "charging", "to charge", "charged"]),
    correctAnswer: "to charge",
    explanation: "'Need' dan keyin infinitiv: 'to charge'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 23
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "That's our neighbour ___ gives us ice cream.",
    options: JSON.stringify(["where", "who", "which", "what"]),
    correctAnswer: "who",
    explanation: "Odam haqida relative clause: 'who'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 24
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "This is the cupboard ___ we keep the dishes.",
    options: JSON.stringify(["where", "that", "who", "which"]),
    correctAnswer: "where",
    explanation: "Joyni bildiruvchi gapda 'where' ishlatiladi.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 25
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Asha ___ go to bed early tonight - there's no school tomorrow.",
    options: JSON.stringify(["has to", "can't", "mustn't", "doesn't have to"]),
    correctAnswer: "doesn't have to",
    explanation: "Majburiyat yo'qligini bildiradi: 'doesn't have to'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 26
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "We don't have ___ to cook risotto.",
    options: JSON.stringify(["rice enough", "some rice", "too many rice", "enough rice"]),
    correctAnswer: "enough rice",
    explanation: "'Enough' otdan oldin keladi: 'enough rice'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 27
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Don't eat ___ cake - it isn't good for you.",
    options: JSON.stringify(["too many", "too", "too much", "some"]),
    correctAnswer: "too much",
    explanation: "Sanalmaydigan/miqdor ma'nosida 'cake' bilan 'too much'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 28
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Lucia fell and cut her knee when she ___ in the park.",
    options: JSON.stringify(["ran", "was running", "is running", "was run"]),
    correctAnswer: "was running",
    explanation: "Uzoqroq davom etayotgan fon harakati: 'was running'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 29
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "While Bruno was playing football yesterday, he ___ his ankle.",
    options: JSON.stringify(["was hurt", "was hurting", "did hurt", "hurt"]),
    correctAnswer: "hurt",
    explanation: "Asosiy qisqa voqea Past Simple bilan beriladi: 'hurt'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 30
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "The shoe shop on Main Street isn't ___ as the one in the shopping centre.",
    options: JSON.stringify(["bigger", "the biggest", "as big", "big"]),
    correctAnswer: "as big",
    explanation: "Teng qiyoslash shakli: 'as ... as'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 31
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "These are ___ smartphones in the shop.",
    options: JSON.stringify(["better", "most good", "the best", "more better"]),
    correctAnswer: "the best",
    explanation: "Ustunlik darajasi: 'the best'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 32
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Mr. Nelson ___ for a present for his wife tomorrow.",
    options: JSON.stringify(["going look", "is going to look", "looking", "looks"]),
    correctAnswer: "is going to look",
    explanation: "Reja/niyat uchun 'is going to look'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 33
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Students ___ tests in the future.",
    options: JSON.stringify(["won't take", "aren't taking", "don't take", "won't taking"]),
    correctAnswer: "won't take",
    explanation: "Kelajak inkori: 'won't + verb'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 34
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "If you study every day, ___ all your exams.",
    options: JSON.stringify(["you passed", "you're passing", "you pass", "you'll pass"]),
    correctAnswer: "you'll pass",
    explanation: "1-tip shart gapi: if + Present Simple, will + verb.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 35
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "You won't understand the lesson if you ___ the coursebook.",
    options: JSON.stringify(["didn't read", "don't read", "won't read", "aren't reading"]),
    correctAnswer: "don't read",
    explanation: "1-tip shart gapida if qismida Present Simple ishlatiladi.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 36
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "___ Yusuf ever been to Japan?",
    options: JSON.stringify(["Have", "Did", "Was", "Has"]),
    correctAnswer: "Has",
    explanation: "Present Perfect savolda 3-shaxs birlik uchun 'Has'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 37
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Bianca hasn't emailed Edgar about the trip ___.",
    options: JSON.stringify(["yet", "already", "just", "ago"]),
    correctAnswer: "yet",
    explanation: "Present Perfect inkor gaplarida 'yet' ishlatiladi.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 38
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "I ___ what you're saying. Can you repeat, please?",
    options: JSON.stringify(["am not understanding", "don't understand", "won't understand", "aren't understand"]),
    correctAnswer: "don't understand",
    explanation: "'Understand' stative verb, odatda Simple shaklda ishlatiladi.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 39
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "You should avoid ___ too much money.",
    options: JSON.stringify(["spend", "spending", "to spend", "spent"]),
    correctAnswer: "spending",
    explanation: "'Avoid' dan keyin gerund (-ing) keladi.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 40
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Mira hasn't eaten any meat ___ two years.",
    options: JSON.stringify(["last", "since", "in", "for"]),
    correctAnswer: "for",
    explanation: "Davomiy muddat bilan 'for' ishlatiladi.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 41
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Giovanni's got ___ ideas for the video competition.",
    options: JSON.stringify(["any", "a few", "a little", "much"]),
    correctAnswer: "a few",
    explanation: "Sanaladigan ko'plik ot 'ideas' bilan 'a few' ishlatiladi.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 42
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "The train ___ at six tomorrow morning.",
    options: JSON.stringify(["leaves", "is leaving", "will leave", "is going to leave"]),
    correctAnswer: "leaves",
    explanation: "Jadval/rasmiy vaqtlar uchun Present Simple: 'leaves'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 43
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "They won’t win the competition unless they ___.",
    options: JSON.stringify(["won't practise", "don't practise", "practise", "will practise"]),
    correctAnswer: "practise",
    explanation: "'Unless' dan keyin Present Simple keladi.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 44
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "That ___ be Marcel's suitcase. It hasn't got his name on it!",
    options: JSON.stringify(["must", "can't", "might", "could"]),
    correctAnswer: "can't",
    explanation: "Ishonchli inkor xulosa: 'can't be'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 45
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "If Hilda had the money, ___ her uncle in Berlin.",
    options: JSON.stringify(["she'll visit", "she visits", "she'd visit", "she's visiting"]),
    correctAnswer: "she'd visit",
    explanation: "2-tip shart gapi: if + Past Simple, would + verb.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 46
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Mrs. Miller, ___ is our neighbour, has got a cute little dog.",
    options: JSON.stringify(["who", "whose", "that", "which"]),
    correctAnswer: "who",
    explanation: "Non-defining relative clause odam uchun 'who'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 47
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "The thieves ___ last night by two police officers.",
    options: JSON.stringify(["caught", "are caught", "catch", "were caught"]),
    correctAnswer: "were caught",
    explanation: "O'tgan zamon majhul nisbat: 'were caught'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 48
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Sophie wants to ___ at the hairdresser's tomorrow.",
    options: JSON.stringify(["cut her hair", "have cut her hair", "has her hair cut", "have her hair cut"]),
    correctAnswer: "have her hair cut",
    explanation: "Xizmat qildirish ma'nosi: 'have her hair cut'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 49
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "The students said they ___ on the project.",
    options: JSON.stringify(["are working", "were working", "work", "have worked"]),
    correctAnswer: "were working",
    explanation: "Reported speechda Present Continuous -> Past Continuous.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 50
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Who ___ this essay?",
    options: JSON.stringify(["did write", "wrote", "write", "you wrote"]),
    correctAnswer: "wrote",
    explanation: "Subject questionda 'did' kerak emas: 'Who wrote...?'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },

  // ════════════════════════════════════════
  // VOCABULARY AND LANGUAGE FUNCTIONS (51 - 100)
  // ════════════════════════════════════════

  // 51
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Your uncle is your mum or dad's ___.",
    options: JSON.stringify(["son", "daughter", "sister", "brother"]),
    correctAnswer: "brother",
    explanation: "Uncle - ota yoki onaning akasi/ukasi.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 52
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Kasia is from Gdańsk. She is ___.",
    options: JSON.stringify(["Poland", "Polish", "of Poland", "from Polish"]),
    correctAnswer: "Polish",
    explanation: "Poland mamlakat, millat/sifat esa 'Polish'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 53
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Burgers are ___.",
    options: JSON.stringify(["fruit", "vegetable", "drink", "meat"]),
    correctAnswer: "meat",
    explanation: "Variantlar ichida burger go'shtli ovqat turiga kiradi.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 54
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Mario ___ up at seven o’clock every morning.",
    options: JSON.stringify(["gets", "does", "leaves", "has"]),
    correctAnswer: "gets",
    explanation: "'Get up' - uyg'onib turmoq.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 55
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Megumi doesn’t enjoy ___.",
    options: JSON.stringify(["travelled", "to travel", "travelling", "travels"]),
    correctAnswer: "travelling",
    explanation: "'Enjoy' dan keyin gerund (-ing) keladi.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 56
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Ismail likes to draw and paint pictures. His favourite school subject is ___.",
    options: JSON.stringify(["Maths", "Art", "PE", "Music"]),
    correctAnswer: "Art",
    explanation: "Rasm chizish va bo'yash fani - Art.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 57
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Caroline puts pens in her ___.",
    options: JSON.stringify(["poster", "pencil case", "calculator", "ruler"]),
    correctAnswer: "pencil case",
    explanation: "Qalam-ruchkalar 'pencil case' ichiga solinadi.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 58
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "You play a ___ with your mouth.",
    options: JSON.stringify(["flute", "violin", "guitar", "cello"]),
    correctAnswer: "flute",
    explanation: "Og'iz bilan chalinadigan asbob - flute.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 59
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Can I ___ a suggestion?",
    options: JSON.stringify(["do", "make", "ask", "take"]),
    correctAnswer: "make",
    explanation: "To'g'ri birikma: 'make a suggestion'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 60
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Lori goes ___ in the park every weekend.",
    options: JSON.stringify(["skiing", "roller skating", "surfing", "swimming"]),
    correctAnswer: "roller skating",
    explanation: "Parkda qilinadigan mos faoliyat - roller skating.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 61
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "We use our ___ to listen to music.",
    options: JSON.stringify(["keyboard", "console", "printer", "headphones"]),
    correctAnswer: "headphones",
    explanation: "Musiqa tinglash uchun headphones ishlatiladi.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 62
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Sven's dad drives an old ___.",
    options: JSON.stringify(["car", "motorbike", "plane", "bicycle"]),
    correctAnswer: "car",
    explanation: "'Drives' fe'li odatda car bilan ishlatiladi.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 63
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Excuse me, ___ to Main Street?",
    options: JSON.stringify(["how do I turn", "how do I take", "how do I get", "how do I miss"]),
    correctAnswer: "how do I get",
    explanation: "Yo'l so'rash iborasi: 'How do I get to...?'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 64
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Seb wants to be a ___ and has just bought a new camera.",
    options: JSON.stringify(["singer", "photographer", "painter", "writer"]),
    correctAnswer: "photographer",
    explanation: "Kamera bilan ishlaydigan kasb - photographer.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 65
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "I think that new film is great! What ___ it?",
    options: JSON.stringify(["do you feel of", "opinion have you got for", "do you think of", "do you feel about"]),
    correctAnswer: "do you think of",
    explanation: "Fikr so'rash: 'What do you think of it?'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 66
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "We wear ___ on our feet.",
    options: JSON.stringify(["boots", "jeans", "earrings", "shorts"]),
    correctAnswer: "boots",
    explanation: "Oyoqqa kiyiladigan narsa - boots.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 67
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "This art festival is very ___!",
    options: JSON.stringify(["interested", "interest", "interesting", "interests"]),
    correctAnswer: "interesting",
    explanation: "Narsani tasvirlash uchun 'interesting' ishlatiladi.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 68
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Claire is ___ because she reads lots of books and knows lots of things.",
    options: JSON.stringify(["kind", "funny", "rude", "clever"]),
    correctAnswer: "clever",
    explanation: "Ko'p biladigan odam - clever.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 69
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "A ___ has got feathers.",
    options: JSON.stringify(["gorilla", "bird", "goat", "snake"]),
    correctAnswer: "bird",
    explanation: "Patlari bor hayvon - bird.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 70
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "I didn’t mean to say that to you. I feel ___ now.",
    options: JSON.stringify(["terrible", "hungry", "great", "cheerful"]),
    correctAnswer: "terrible",
    explanation: "Noto'g'ri gapirib qo'yganda o'zini yomon his qilish: 'terrible'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 71
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Marius listens to music on his ___ when he studies in the library.",
    options: JSON.stringify(["digital camera", "games console", "wireless earbuds", "Bluetooth® speaker"]),
    correctAnswer: "wireless earbuds",
    explanation: "Kutubxonada shaxsiy tinglash uchun wireless earbuds mos.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 72
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Kenji needs to ___ apps for his mum.",
    options: JSON.stringify(["charge", "play", "download", "phone"]),
    correctAnswer: "download",
    explanation: "Ilovalarni telefonga yuklash - download apps.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 73
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Don’t forget to say goodbye before you hang ___.",
    options: JSON.stringify(["out", "off", "on", "up"]),
    correctAnswer: "up",
    explanation: "Telefonni qo'yish: 'hang up'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 74
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Dominic cooks food in the ___.",
    options: JSON.stringify(["cupboard", "microwave", "fridge", "dishwasher"]),
    correctAnswer: "microwave",
    explanation: "Ovqat isitish/pishirish uchun microwave ishlatiladi.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 75
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Fraser doesn’t like to tidy his ___ on Saturdays.",
    options: JSON.stringify(["rug", "washing up", "shopping", "room"]),
    correctAnswer: "room",
    explanation: "'Tidy your room' - xonani tartibga keltirish.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 76
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "What do you think ___?",
    options: JSON.stringify(["I should do", "should I do", "should I to do", "I should doing"]),
    correctAnswer: "I should do",
    explanation: "Indirect question tartibi: 'What do you think I should do?'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 77
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Your ___ is part of your arm.",
    options: JSON.stringify(["knee", "ankle", "elbow", "throat"]),
    correctAnswer: "elbow",
    explanation: "Qo'lning bukiladigan qismi - elbow.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 78
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Tamara and Penny ___ badminton every weekend.",
    options: JSON.stringify(["go", "keep", "do", "play"]),
    correctAnswer: "play",
    explanation: "Badminton bilan 'play' ishlatiladi.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 79
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Robin is coughing, and he has a headache. He’s got the ___.",
    options: JSON.stringify(["flu", "fever", "cold", "temperature"]),
    correctAnswer: "flu",
    explanation: "'The flu' - gripp; cough va headache bilan mos.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 80
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "I’m ill today. I think I should stay in ___.",
    options: JSON.stringify(["calm", "doctor", "careful", "bed"]),
    correctAnswer: "bed",
    explanation: "Kasal bo'lganda 'stay in bed' deyiladi.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 81
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "You can buy carrots at the ___.",
    options: JSON.stringify(["pharmacy", "greengrocer's", "florist's", "newsagent's"]),
    correctAnswer: "greengrocer's",
    explanation: "Sabzavotlar greengrocer's do'konida sotiladi.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 82
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Hana sorts the rubbish and ___ pocket money from her parents every Friday.",
    options: JSON.stringify(["lends", "buys", "borrows", "gets"]),
    correctAnswer: "gets",
    explanation: "Pul olish - 'get pocket money'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 83
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Have you got this jacket in ___ colour?",
    options: JSON.stringify(["other", "another", "a smaller", "a bigger"]),
    correctAnswer: "another",
    explanation: "Boshqa rang so'rash: 'another colour'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 84
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "___ draw pictures of houses and other buildings.",
    options: JSON.stringify(["Architects", "Mechanics", "Scientists", "Builders"]),
    correctAnswer: "Architects",
    explanation: "Binolar loyihasini chizadiganlar - architects.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 85
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Yuki works ___ a receptionist.",
    options: JSON.stringify(["as", "-", "for", "like"]),
    correctAnswer: "as",
    explanation: "Kasb/vazifa sifatida ishlash: 'work as'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 86
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "We ___ a lot of exercises in English lessons.",
    options: JSON.stringify(["make", "give", "do", "write"]),
    correctAnswer: "do",
    explanation: "Mashqlar bajarish: 'do exercises'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 87
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "My cousin lives ___ the coast in the north of Spain.",
    options: JSON.stringify(["at", "by", "in", "on"]),
    correctAnswer: "on",
    explanation: "Sohil bo'yida yashash: 'live on the coast'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 88
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "The ___ of our city is 55,000 people.",
    options: JSON.stringify(["money", "border", "capital", "population"]),
    correctAnswer: "population",
    explanation: "Aholi soni - population.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 89
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "My brother ___ many sports stars on social media.",
    options: JSON.stringify(["follows", "connects", "adds", "chats"]),
    correctAnswer: "follows",
    explanation: "Ijtimoiy tarmoqlarda odamlarni 'follow' qilishadi.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 90
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "A: I do not know how to edit the video.\nB: ___ look online?",
    options: JSON.stringify(["How do you", "Why don’t we", "What about", "Shall you"]),
    correctAnswer: "Why don’t we",
    explanation: "Taklif shakli: 'Why don't we look online?'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 91
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Last night, there was some ___ snow.",
    options: JSON.stringify(["heavy", "large", "strong", "icy"]),
    correctAnswer: "heavy",
    explanation: "Qor kuchli yog'sa 'heavy snow' deyiladi.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 92
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "It’s hot and dry, and it hasn’t rained for a long time. It’s a ___.",
    options: JSON.stringify(["flood", "drought", "shower", "hurricane"]),
    correctAnswer: "drought",
    explanation: "Uzoq vaqt yomg'ir yog'masa - drought.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 93
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "On Sundays, Dad cooks ___ chicken in the oven.",
    options: JSON.stringify(["raw", "mint", "boiled", "roast"]),
    correctAnswer: "roast",
    explanation: "Duxovkada pishgan tovuq - roast chicken.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 94
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Would you like ___ to eat?",
    options: JSON.stringify(["some else", "anything else", "something other", "nothing else"]),
    correctAnswer: "anything else",
    explanation: "Taklif/so'rovda 'anything else' ishlatiladi.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 95
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "We’d rather ___ a comedy tonight.",
    options: JSON.stringify(["not watch", "not to watch", "aren’t watching", "don’t watch"]),
    correctAnswer: "not watch",
    explanation: "'Would rather' dan keyin infinitivsiz fe'l keladi.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 96
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "We use ___ to play baseball or cricket.",
    options: JSON.stringify(["a racket", "a snorkel", "a mat", "a bat"]),
    correctAnswer: "a bat",
    explanation: "Baseball/cricket uchun bat ishlatiladi.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 97
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "The Newcastle United football team has many ___.",
    options: JSON.stringify(["supports", "support", "supporters", "supporting"]),
    correctAnswer: "supporters",
    explanation: "Jamoani qo'llab-quvvatlaydigan odamlar - supporters.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 98
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "A type of holiday accommodation for one person is called a ___.",
    options: JSON.stringify(["check in", "single room", "view", "double room"]),
    correctAnswer: "single room",
    explanation: "Bitta odam uchun xona - single room.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 99
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Adem often hangs ___ with his friends in the shopping centre.",
    options: JSON.stringify(["off", "out", "up", "on"]),
    correctAnswer: "out",
    explanation: "Do'stlar bilan vaqt o'tkazish: 'hang out'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 100
  {
    testId: TEST_ID_A,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "A criminal who damages property is ___.",
    options: JSON.stringify(["a robber", "a pickpocket", "a vandal", "a thief"]),
    correctAnswer: "a vandal",
    explanation: "Mulkka zarar yetkazadigan jinoyatchi - vandal.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
];

// ════════════════════════════════════════════════════════════
// B VARIANT SAVOLLARI  (testId = 2)
// ════════════════════════════════════════════════════════════
const TEST_ID_B = 2;

export const questionsB = [
  // ════════════════════════════════
  // GRAMMAR  (1 - 50)
  // ════════════════════════════════

  // 1
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "___ Agnieszka speak Spanish very well?",
    options: JSON.stringify(["Is", "Has", "Can", "Do"]),
    correctAnswer: "Can",
    explanation: "To'g'ri javob: Can.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },

  // 2
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Teresa and Thomas ___ got a cake for Sally’s birthday.",
    options: JSON.stringify(["are", "have", "has", "is"]),
    correctAnswer: "have",
    explanation: "To'g'ri javob: have.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },

  // 3
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "There ___ a great burger bar in town.",
    options: JSON.stringify(["is", "have", "has", "are"]),
    correctAnswer: "is",
    explanation: "To'g'ri javob: is.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },

  // 4
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Rosita ___ on Sundays.",
    options: JSON.stringify(["study", "does study", "studys", "studies"]),
    correctAnswer: "studies",
    explanation: "To'g'ri javob: studies.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },

  // 5
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Manuel’s mum ___ now.",
    options: JSON.stringify(["isn’t working", "doesn’t work", "aren’t working", "don’t work"]),
    correctAnswer: "isn’t working",
    explanation: "To'g'ri javob: isn’t working.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },

  // 6
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Risa is fourteen. Fadi is sixteen. Risa is ___ than Fadi.",
    options: JSON.stringify(["youngest", "young", "younger", "more young"]),
    correctAnswer: "younger",
    explanation: "To'g'ri javob: younger.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },

  // 7
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "___ there a race yesterday?",
    options: JSON.stringify(["Is", "Were", "Are", "Was"]),
    correctAnswer: "Was",
    explanation: "To'g'ri javob: Was.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },

  // 8
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Verity ___ a big competition last week!",
    options: JSON.stringify(["winned", "winning", "win", "won"]),
    correctAnswer: "won",
    explanation: "To'g'ri javob: won.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },

  // 9
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Did you ___ Dolly last night?",
    options: JSON.stringify(["sawed", "see", "saw", "seeing"]),
    correctAnswer: "see",
    explanation: "To'g'ri javob: see.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },

  // 10
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Don’t speak! You ___ speak during the exam.",
    options: JSON.stringify(["have to", "has to", "mustn’t", "don’t have to"]),
    correctAnswer: "mustn’t",
    explanation: "To'g'ri javob: mustn’t.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },

  // 11
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "There was a pizza on the plate. ___ pizza was cold.",
    options: JSON.stringify(["There", "The", "An", "A"]),
    correctAnswer: "The",
    explanation: "To'g'ri javob: The.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },

  // 12
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Pierre ___ to the match tomorrow.",
    options: JSON.stringify(["go", "is going", "goes", "going"]),
    correctAnswer: "is going",
    explanation: "To'g'ri javob: is going.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },

  // 13
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "They ___ films every night.",
    options: JSON.stringify(["don’t watching", "don’t watch", "aren’t watching", "doesn’t watch"]),
    correctAnswer: "don’t watch",
    explanation: "To'g'ri javob: don’t watch.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },

  // 14
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Where ___ live?",
    options: JSON.stringify(["is your uncle", "do your uncle", "does your uncle", "your uncle does"]),
    correctAnswer: "does your uncle",
    explanation: "To'g'ri javob: does your uncle.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },

  // 15
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Hi, Paul. What ___?",
    options: JSON.stringify(["do you do", "you do", "are you doing", "are you do"]),
    correctAnswer: "are you doing",
    explanation: "To'g'ri javob: are you doing.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },

  // 16
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Aika and Dai usually listen to hip-hop, but today they ___ to some jazz.",
    options: JSON.stringify(["listen", "is listening", "listening", "are listening"]),
    correctAnswer: "are listening",
    explanation: "To'g'ri javob: are listening.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },

  // 17
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "There ___ a big party in our classroom yesterday.",
    options: JSON.stringify(["was", "had", "were", "is"]),
    correctAnswer: "was",
    explanation: "To'g'ri javob: was.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },

  // 18
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Anita ___ cat food this morning.",
    options: JSON.stringify(["didn’t bought", "doesn’t buy", "doesn’t bought", "didn’t buy"]),
    correctAnswer: "didn’t buy",
    explanation: "To'g'ri javob: didn’t buy.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },

  // 19
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Hassan ___ that online game when he was little.",
    options: JSON.stringify(["use to play", "used play", "used to play", "used to playing"]),
    correctAnswer: "used to play",
    explanation: "To'g'ri javob: used to play.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },

  // 20
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "___ have a digital camera five years ago?",
    options: JSON.stringify(["Does she used", "Did she use to", "Did she used to", "Does she used to"]),
    correctAnswer: "Did she use to",
    explanation: "To'g'ri javob: Did she use to.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },

  // 21
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Diana keeps ___ the time!",
    options: JSON.stringify(["checks", "to check", "checking", "check"]),
    correctAnswer: "checking",
    explanation: "To'g'ri javob: checking.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },

  // 22
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Edward needs ___ a video clip.",
    options: JSON.stringify(["make", "to make", "making", "makes"]),
    correctAnswer: "to make",
    explanation: "To'g'ri javob: to make.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },

  // 23
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "There’s my neighbour ___ plays the piano.",
    options: JSON.stringify(["who", "which", "what", "where"]),
    correctAnswer: "who",
    explanation: "To'g'ri javob: who.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },

  // 24
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "That’s the wardrobe ___ we keep our clothes.",
    options: JSON.stringify(["which", "who", "where", "that"]),
    correctAnswer: "where",
    explanation: "To'g'ri javob: where.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },

  // 25
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Marta ___ revise tonight. There’s no Maths test tomorrow.",
    options: JSON.stringify(["has to", "doesn’t have to", "mustn’t", "can’t"]),
    correctAnswer: "doesn’t have to",
    explanation: "To'g'ri javob: doesn’t have to.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },

  // 26
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "We don’t have ___ to make a salad.",
    options: JSON.stringify(["enough tomatoes", "some tomatoes", "too much tomatoes", "tomatoes enough"]),
    correctAnswer: "enough tomatoes",
    explanation: "To'g'ri javob: enough tomatoes.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },

  // 27
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Don’t eat ___ burgers – they are not good for you.",
    options: JSON.stringify(["too much", "some", "too", "too many"]),
    correctAnswer: "too many",
    explanation: "To'g'ri javob: too many.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },

  // 28
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Jianping fell and broke his arm when he ___ in the park.",
    options: JSON.stringify(["is cycling", "was cycle", "cycled", "was cycling"]),
    correctAnswer: "was cycling",
    explanation: "To'g'ri javob: was cycling.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },

  // 29
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "When Adriana was playing tennis this morning, she ___ her elbow.",
    options: JSON.stringify(["was hurt", "hurt", "did hurt", "was hurting"]),
    correctAnswer: "hurt",
    explanation: "To'g'ri javob: hurt.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },

  // 30
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "The bakery near our house isn’t ___ as the one in town.",
    options: JSON.stringify(["more big", "as big", "big", "the biggest"]),
    correctAnswer: "as big",
    explanation: "To'g'ri javob: as big.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },

  // 31
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "These are ___ boots in the shop.",
    options: JSON.stringify(["the best", "better", "more best", "most good"]),
    correctAnswer: "the best",
    explanation: "To'g'ri javob: the best.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },

  // 32
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Mrs. Garvey ___ a new smartphone for her son tonight.",
    options: JSON.stringify(["is buy", "buys", "going buy", "is going to buy"]),
    correctAnswer: "is going to buy",
    explanation: "To'g'ri javob: is going to buy.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },

  // 33
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "We ___ other languages in the future.",
    options: JSON.stringify(["don’t learn", "aren’t learning", "won’t learn", "won’t learning"]),
    correctAnswer: "won’t learn",
    explanation: "To'g'ri javob: won’t learn.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },

  // 34
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "If you work hard, ___ a good mark.",
    options: JSON.stringify(["you’re getting", "you’ll get", "you’ve get", "you got"]),
    correctAnswer: "you’ll get",
    explanation: "To'g'ri javob: you’ll get.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },

  // 35
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "You won’t understand the lesson if you ___ questions.",
    options: JSON.stringify(["aren’t asking", "didn’t ask", "won’t ask", "don’t ask"]),
    correctAnswer: "don’t ask",
    explanation: "To'g'ri javob: don’t ask.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },

  // 36
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "___ Alfredo ever been to China?",
    options: JSON.stringify(["Has", "Was", "Did", "Have"]),
    correctAnswer: "Has",
    explanation: "To'g'ri javob: Has.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },

  // 37
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Valentina hasn’t texted Jason about the holiday ___.",
    options: JSON.stringify(["just", "yet", "ago", "already"]),
    correctAnswer: "yet",
    explanation: "To'g'ri javob: yet.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },

  // 38
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Sorry, I ___ how to upload the pictures. Can you help me?",
    options: JSON.stringify(["don’t know", "won’t know", "am not knowing", "aren’t knowing"]),
    correctAnswer: "don’t know",
    explanation: "To'g'ri javob: don’t know.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },

  // 39
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "You should practise ___ selfies.",
    options: JSON.stringify(["take", "to take", "took", "taking"]),
    correctAnswer: "taking",
    explanation: "To'g'ri javob: taking.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },

  // 40
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Yasmin hasn’t drunk any milk ___ three weeks.",
    options: JSON.stringify(["for", "since", "in", "last"]),
    correctAnswer: "for",
    explanation: "To'g'ri javob: for.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },

  // 41
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "I always add ___ sugar to my tea.",
    options: JSON.stringify(["many", "a few", "any", "a little"]),
    correctAnswer: "a little",
    explanation: "To'g'ri javob: a little.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },

  // 42
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "The Maths lesson ___ at 10 a.m. tomorrow.",
    options: JSON.stringify(["will start", "starts", "is starting", "is going to start"]),
    correctAnswer: "starts",
    explanation: "To'g'ri javob: starts.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },

  // 43
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "You won’t find out unless you ___!",
    options: JSON.stringify(["will ask", "don’t ask", "won’t ask", "ask"]),
    correctAnswer: "ask",
    explanation: "To'g'ri javob: ask.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },

  // 44
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "That ___ be Uma’s backpack. It’s got her name on it.",
    options: JSON.stringify(["can’t", "might", "must", "could"]),
    correctAnswer: "must",
    explanation: "To'g'ri javob: must.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },

  // 45
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "If Rodolfo had more time, ___ to his grandparents every day.",
    options: JSON.stringify(["he’s speaking", "he’d speak", "he’ll speak", "he spoke"]),
    correctAnswer: "he’d speak",
    explanation: "To'g'ri javob: he’d speak.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },

  // 46
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Green Park, ___ is huge, has a very big lake.",
    options: JSON.stringify(["where", "that", "which", "who"]),
    correctAnswer: "which",
    explanation: "To'g'ri javob: which.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },

  // 47
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "The report ___ yesterday by a detective.",
    options: JSON.stringify(["is written", "was written", "write", "wrote"]),
    correctAnswer: "was written",
    explanation: "To'g'ri javob: was written.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },

  // 48
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Peter needs to ___ at the dentist.",
    options: JSON.stringify(["have checked his teeth", "has his teeth checked", "have his teeth checked", "check his teeth"]),
    correctAnswer: "have his teeth checked",
    explanation: "To'g'ri javob: have his teeth checked.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },

  // 49
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "The students said they ___ an exciting debate at school.",
    options: JSON.stringify(["have planned", "plan", "are planning", "were planning"]),
    correctAnswer: "were planning",
    explanation: "To'g'ri javob: were planning.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },

  // 50
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Who ___ this book?",
    options: JSON.stringify(["did bring", "brought", "bring", "you brought"]),
    correctAnswer: "brought",
    explanation: "To'g'ri javob: brought.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },

  // ════════════════════════════════
  // VOCABULARY AND LANGUAGE FUNCTIONS (51 - 100)
  // ════════════════════════════════

  // 51
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Your aunt is your mum or dad’s ___.",
    options: JSON.stringify(["brother", "sister", "daughter", "son"]),
    correctAnswer: "sister",
    explanation: "To'g'ri javob: sister.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },

  // 52
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Dario is from Venice. He is ___.",
    options: JSON.stringify(["of Italy", "Italy", "Italian", "from Italian"]),
    correctAnswer: "Italian",
    explanation: "To'g'ri javob: Italian.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },

  // 53
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Burgers are ___.",
    options: JSON.stringify(["vegetable", "drink", "meat", "fruit"]),
    correctAnswer: "meat",
    explanation: "To'g'ri javob: meat.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },

  // 54
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Nadine and Georgia ___ up at 6.30 every morning.",
    options: JSON.stringify(["go", "leave", "wake", "have"]),
    correctAnswer: "wake",
    explanation: "To'g'ri javob: wake.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },

  // 55
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Ramon doesn’t enjoy ___.",
    options: JSON.stringify(["singing", "singers", "to sing", "sings"]),
    correctAnswer: "singing",
    explanation: "To'g'ri javob: singing.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },

  // 56
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Jemima likes to draw and paint pictures. Her favourite school subject is ___.",
    options: JSON.stringify(["English", "IT", "History", "Art"]),
    correctAnswer: "Art",
    explanation: "To'g'ri javob: Art.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },

  // 57
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Alan keeps pens in his ___.",
    options: JSON.stringify(["ruler", "dictionary", "rubber", "pencil case"]),
    correctAnswer: "pencil case",
    explanation: "To'g'ri javob: pencil case.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },

  // 58
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "You play a ___ with your mouth.",
    options: JSON.stringify(["violin", "saxophone", "guitar", "cello"]),
    correctAnswer: "saxophone",
    explanation: "To'g'ri javob: saxophone.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },

  // 59
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Can I ___ a suggestion?",
    options: JSON.stringify(["take", "ask", "do", "make"]),
    correctAnswer: "make",
    explanation: "To'g'ri javob: make.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },

  // 60
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Kamil is a great skater. He has got two medals for ___.",
    options: JSON.stringify(["cycling", "judo", "basketball", "ice hockey"]),
    correctAnswer: "ice hockey",
    explanation: "To'g'ri javob: ice hockey.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },

  // 61
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "We use our ___ to listen to music.",
    options: JSON.stringify(["keyboard", "headphones", "printer", "console"]),
    correctAnswer: "headphones",
    explanation: "To'g'ri javob: headphones.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },

  // 62
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Ellie’s mum drives a red ___.",
    options: JSON.stringify(["bicycle", "plane", "car", "motorbike"]),
    correctAnswer: "car",
    explanation: "To'g'ri javob: car.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },

  // 63
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Excuse me, ___ to Main Street?",
    options: JSON.stringify(["how do I get", "how do I miss", "how do I turn", "how do I take"]),
    correctAnswer: "how do I get",
    explanation: "To'g'ri javob: how do I get.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },

  // 64
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Joni wants to be a ___. She knows lots of songs.",
    options: JSON.stringify(["musician", "painter", "singer", "photographer"]),
    correctAnswer: "singer",
    explanation: "To'g'ri javob: singer.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },

  // 65
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "We love the new film! How ___ it?",
    options: JSON.stringify(["do you feel about", "do you think about", "do you feel of", "is your opinion"]),
    correctAnswer: "do you feel about",
    explanation: "To'g'ri javob: do you feel about.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },

  // 66
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "They wear ___ on their hands.",
    options: JSON.stringify(["trousers", "shoes", "glasses", "gloves"]),
    correctAnswer: "gloves",
    explanation: "To'g'ri javob: gloves.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },

  // 67
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Oh no, Enrico’s friends went to the festival without him! Now he feels ___.",
    options: JSON.stringify(["annoyed", "annoy", "annoying", "annoys"]),
    correctAnswer: "annoyed",
    explanation: "To'g'ri javob: annoyed.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },

  // 68
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Lucia is a ___ person because she usually talks a lot.",
    options: JSON.stringify(["shy", "chatty", "tidy", "selfish"]),
    correctAnswer: "chatty",
    explanation: "To'g'ri javob: chatty.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },

  // 69
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "A ___ has got fur.",
    options: JSON.stringify(["parrot", "ladybird", "polar bear", "tortoise"]),
    correctAnswer: "polar bear",
    explanation: "To'g'ri javob: polar bear.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },

  // 70
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "I didn’t mean to say that to you. I feel ___ now.",
    options: JSON.stringify(["happy", "polite", "bored", "terrible"]),
    correctAnswer: "terrible",
    explanation: "To'g'ri javob: terrible.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },

  // 71
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Winona takes photos with her ___.",
    options: JSON.stringify(["headset", "digital camera", "charger", "earbuds"]),
    correctAnswer: "digital camera",
    explanation: "To'g'ri javob: digital camera.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },

  // 72
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Rasheed usually ___ apps for his grandfather.",
    options: JSON.stringify(["takes", "downloads", "phones", "charges"]),
    correctAnswer: "downloads",
    explanation: "To'g'ri javob: downloads.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },

  // 73
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "We found ___ about the festival on this website.",
    options: JSON.stringify(["on", "at", "in", "out"]),
    correctAnswer: "out",
    explanation: "To'g'ri javob: out.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },

  // 74
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Aurelia keeps her clothes in the ___.",
    options: JSON.stringify(["ceiling", "dishwasher", "wardrobe", "microwave"]),
    correctAnswer: "wardrobe",
    explanation: "To'g'ri javob: wardrobe.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },

  // 75
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "After dinner, Mr. Mendes takes out the ___.",
    options: JSON.stringify(["rubbish", "dishwasher", "cooking", "washing up"]),
    correctAnswer: "rubbish",
    explanation: "To'g'ri javob: rubbish.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },

  // 76
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "What do you think ___?",
    options: JSON.stringify(["should Audrey do", "Audrey should do", "should Audrey to do", "Audrey should doing"]),
    correctAnswer: "Audrey should do",
    explanation: "To'g'ri javob: Audrey should do.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },

  // 77
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Your ___ is part of your leg.",
    options: JSON.stringify(["finger", "ankle", "shoulder", "neck"]),
    correctAnswer: "ankle",
    explanation: "To'g'ri javob: ankle.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },

  // 78
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Hector and Terry usually ___ running after school.",
    options: JSON.stringify(["do", "play", "keep", "go"]),
    correctAnswer: "go",
    explanation: "To'g'ri javob: go.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },

  // 79
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Luisa is sneezing a lot. She’s got ___ fever.",
    options: JSON.stringify(["hay", "sore", "stomach", "cold"]),
    correctAnswer: "hay",
    explanation: "To'g'ri javob: hay.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },

  // 80
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Niall’s back is sore. He should lie ___.",
    options: JSON.stringify(["calm", "bed", "down", "careful"]),
    correctAnswer: "down",
    explanation: "To'g'ri javob: down.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },

  // 81
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "We can buy medicine at the ___.",
    options: JSON.stringify(["butcher’s", "greengrocer’s", "pharmacy", "newsagent’s"]),
    correctAnswer: "pharmacy",
    explanation: "To'g'ri javob: pharmacy.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },

  // 82
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Destan ___ pocket money for doing the washing up.",
    options: JSON.stringify(["borrows", "buys", "lends", "earns"]),
    correctAnswer: "earns",
    explanation: "To'g'ri javob: earns.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },

  // 83
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "These hoodies are in the ___.",
    options: JSON.stringify(["size", "colour", "sale", "change"]),
    correctAnswer: "sale",
    explanation: "To'g'ri javob: sale.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },

  // 84
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "A ___ writes articles about the news.",
    options: JSON.stringify(["lawyer", "journalist", "manager", "receptionist"]),
    correctAnswer: "journalist",
    explanation: "To'g'ri javob: journalist.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },

  // 85
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Yogesh works ___ a builder.",
    options: JSON.stringify(["like", "at", "–", "as"]),
    correctAnswer: "as",
    explanation: "To'g'ri javob: as.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },

  // 86
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "We ___ a lot of notes in Biology lessons.",
    options: JSON.stringify(["make", "give", "do", "write"]),
    correctAnswer: "write",
    explanation: "To'g'ri javob: write.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },

  // 87
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "My uncle lives ___ an island off Italy.",
    options: JSON.stringify(["in", "on", "at", "by"]),
    correctAnswer: "on",
    explanation: "To'g'ri javob: on.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },

  // 88
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "We live in a small town, near the ___ with Argentina.",
    options: JSON.stringify(["border", "capital city", "cliff", "population"]),
    correctAnswer: "border",
    explanation: "To'g'ri javob: border.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },

  // 89
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "My sister ___ many celebrities on social media.",
    options: JSON.stringify(["chats", "adds", "connects", "follows"]),
    correctAnswer: "follows",
    explanation: "To'g'ri javob: follows.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },

  // 90
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "A: I’m not sure how to edit the video. B: ___ looking online?",
    options: JSON.stringify(["How do", "What about", "Why don’t", "Shall we"]),
    correctAnswer: "What about",
    explanation: "To'g'ri javob: What about.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },

  // 91
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "It’s ___ hot here – please open the windows.",
    options: JSON.stringify(["boiling", "mild", "strong", "freezing"]),
    correctAnswer: "boiling",
    explanation: "To'g'ri javob: boiling.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },

  // 92
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "It’s rained a lot today. I think we are going to have a ___.",
    options: JSON.stringify(["hurricane", "shower", "drought", "flood"]),
    correctAnswer: "flood",
    explanation: "To'g'ri javob: flood.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },

  // 93
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "My brother loves ___ carrots, he never cooks them.",
    options: JSON.stringify(["raw", "frozen", "boiled", "mint"]),
    correctAnswer: "raw",
    explanation: "To'g'ri javob: raw.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },

  // 94
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Would you like ___ to eat?",
    options: JSON.stringify(["some else", "nothing else", "something other", "anything else"]),
    correctAnswer: "anything else",
    explanation: "To'g'ri javob: anything else.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },

  // 95
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "I’d rather ___ to the theatre tonight.",
    options: JSON.stringify(["am not going", "not to go", "not go", "don’t go"]),
    correctAnswer: "not go",
    explanation: "To'g'ri javob: not go.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },

  // 96
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "We use ___ to play tennis.",
    options: JSON.stringify(["a bat", "a snorkel", "a racket", "a mat"]),
    correctAnswer: "a racket",
    explanation: "To'g'ri javob: a racket.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },

  // 97
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Elin plays football. She’s a ___.",
    options: JSON.stringify(["defends", "defender", "defend", "defending"]),
    correctAnswer: "defender",
    explanation: "To'g'ri javob: defender.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },

  // 98
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "A type of holiday accommodation for two people is a ___.",
    options: JSON.stringify(["view", "single room", "reservation", "double room"]),
    correctAnswer: "double room",
    explanation: "To'g'ri javob: double room.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },

  // 99
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "I hang ___ with my friends in the park.",
    options: JSON.stringify(["off", "on", "up", "out"]),
    correctAnswer: "out",
    explanation: "To'g'ri javob: out.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },

  // 100
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "A criminal who goes into houses to steal things is ___.",
    options: JSON.stringify(["a vandal", "a shoplifter", "a burglar", "a pickpocket"]),
    correctAnswer: "a burglar",
    explanation: "To'g'ri javob: a burglar.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
];

// ════════════════════════════════════════════════════════════
// IKKALA VARIANTNI BIRGA EXPORT QILISH
// ════════════════════════════════════════════════════════════
export const allQuestions = [...questionsA, ...questionsB];

export default allQuestions;
