
// testId = 1  →  Bu savollar birinchi testga tegishli
const TEST_ID = 1;

export const questions = [
  // ════════════════════════════════════════
  // GRAMMAR  (1 – 50)
  // ════════════════════════════════════════

  // 1
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "I ___ twelve years old.",
    options: JSON.stringify(["are", "have", "am", "is"]),
    correctAnswer: "am",
    explanation: "'I' bilan 'am' ishlatiladi.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 2
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "My cousins ___ British.",
    options: JSON.stringify(["isn't", "haven't", "am not", "aren't"]),
    correctAnswer: "aren't",
    explanation: "'Cousins' ko'plik, shuning uchun 'aren't' to'g'ri.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 3
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Look at ___ T-shirt over there!",
    options: JSON.stringify(["those", "that", "this", "these"]),
    correctAnswer: "that",
    explanation: "'Over there' uzoqdagi birlikni ko'rsatadi: 'that'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 4
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "There ___ two windows in the living room.",
    options: JSON.stringify(["be", "is", "have", "are"]),
    correctAnswer: "are",
    explanation: "'Two windows' ko'plik, shuning uchun 'are' to'g'ri.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 5
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "He ___ blonde hair.",
    options: JSON.stringify(["has got", "have got", "is", "got"]),
    correctAnswer: "has got",
    explanation: "'He' uchun 'has got' ishlatiladi.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 6
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "___ you got blue eyes?",
    options: JSON.stringify(["Is", "Do", "Have", "Has"]),
    correctAnswer: "Have",
    explanation: "'You' bilan 'Have' ishlatiladi.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 7
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Fernanda ___ read.",
    options: JSON.stringify(["isn't", "hasn't", "not", "can't"]),
    correctAnswer: "can't",
    explanation: "Qobiliyat inkorini bildirish uchun 'can't' ishlatiladi.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 8
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "___ Giorgos swim?",
    options: JSON.stringify(["Is", "Can", "Has", "Do"]),
    correctAnswer: "Can",
    explanation: "Qobiliyat so'rovi uchun 'Can' ishlatiladi.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 9
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Dad ___ to music in the evening.",
    options: JSON.stringify(["listening", "listen", "to listen", "listens"]),
    correctAnswer: "listens",
    explanation: "3-shaxs birlik (he/she/it) uchun fe'lga -s qo'shiladi.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 10
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "We ___ get up early.",
    options: JSON.stringify(["don't", "doesn't", "hasn't", "haven't"]),
    correctAnswer: "don't",
    explanation: "'We' bilan inkor uchun 'don't' ishlatiladi.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 11
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "___ cats live in the sea?",
    options: JSON.stringify(["Does", "Are", "Do", "Is"]),
    correctAnswer: "Do",
    explanation: "'Cats' ko'plik, shuning uchun 'Do' ishlatiladi.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 12
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Luca loves ___ basketball.",
    options: JSON.stringify(["play", "playing", "can play", "plays"]),
    correctAnswer: "playing",
    explanation: "'loves' dan keyin gerund (-ing) keladi.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 13
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "___ cat is this?",
    options: JSON.stringify(["Whose", "Why", "When", "Where"]),
    correctAnswer: "Whose",
    explanation: "Egalik so'rash uchun 'Whose' ishlatiladi.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 14
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "I'm looking for Jacob. I think these are ___ keys.",
    options: JSON.stringify(["he", "him", "his", "her"]),
    correctAnswer: "his",
    explanation: "Egalik olmoshi: erkak uchun 'his'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 15
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "There aren't ___ pizzerias in town.",
    options: JSON.stringify(["any", "some", "a", "the"]),
    correctAnswer: "any",
    explanation: "Inkor gaplarda ko'plik bilan 'any' ishlatiladi.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 16
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "How ___ apples have you got?",
    options: JSON.stringify(["much", "some", "many", "any"]),
    correctAnswer: "many",
    explanation: "Sanaladigan otlar bilan 'many' ishlatiladi.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 17
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "There is ___ orange juice in the kitchen.",
    options: JSON.stringify(["some", "an", "any", "many"]),
    correctAnswer: "some",
    explanation: "Tasdiq gapda sanalmaydigan ot bilan 'some' ishlatiladi.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 18
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "What time ___ Marko eat breakfast?",
    options: JSON.stringify(["is", "does", "has", "do"]),
    correctAnswer: "does",
    explanation: "3-shaxs birlik so'rovi uchun 'does' ishlatiladi.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 19
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "The students ___ in the classroom at the moment.",
    options: JSON.stringify(["are talk", "talk", "are talking", "is talking"]),
    correctAnswer: "are talking",
    explanation: "Hozirgi davom zamoni: 'are talking'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 20
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Dima ___ sleeping now.",
    options: JSON.stringify(["don't", "aren't", "hasn't", "isn't"]),
    correctAnswer: "isn't",
    explanation: "'Dima' birlik, hozirgi davom zamoni inkori: 'isn't'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 21
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "George always ___ school at 8.45 in the morning.",
    options: JSON.stringify(["start", "starts", "is starting", "are starting"]),
    correctAnswer: "starts",
    explanation: "'Always' odatiy harakatni bildiradi; 3-shaxs: 'starts'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 22
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "We ___ our homework right now.",
    options: JSON.stringify(["doing", "do", "'re doing", "does"]),
    correctAnswer: "'re doing",
    explanation: "Hozirgi davom zamoni: 'We're doing'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 23
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Rock is ___ than classical music.",
    options: JSON.stringify(["the popular", "most popular", "popular", "more popular"]),
    correctAnswer: "more popular",
    explanation: "Ikki narsani solishtirish: 'more popular'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 24
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "The piano is ___ musical instrument!",
    options: JSON.stringify(["the cooler", "the more cool", "coolest", "the coolest"]),
    correctAnswer: "the coolest",
    explanation: "Ustunlik darajasi: 'the coolest'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 25
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Classical music is ___ music. I love it.",
    options: JSON.stringify(["better", "the better", "the best", "the good"]),
    correctAnswer: "the best",
    explanation: "Ustunlik darajasi: 'the best'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 26
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "___ your friends at the swimming pool last week?",
    options: JSON.stringify(["Was", "Are", "Is", "Were"]),
    correctAnswer: "Were",
    explanation: "'Friends' ko'plik, o'tgan zamon: 'Were'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 27
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "There ___ a lot of people at the school sports day.",
    options: JSON.stringify(["had", "were", "was", "came"]),
    correctAnswer: "were",
    explanation: "'A lot of people' ko'plik, o'tgan zamon: 'were'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 28
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "We ___ tennis last week.",
    options: JSON.stringify(["played", "playing", "play", "plays"]),
    correctAnswer: "played",
    explanation: "O'tgan oddiy zamon: 'played'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 29
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Ben ___ eight kilometres yesterday.",
    options: JSON.stringify(["run", "runs", "ran", "runned"]),
    correctAnswer: "ran",
    explanation: "'run' ning noto'g'ri o'tgan zamoni: 'ran'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 30
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "The match ___ at six o'clock.",
    options: JSON.stringify(["weren't start", "don't start", "didn't started", "didn't start"]),
    correctAnswer: "didn't start",
    explanation: "O'tgan zamon inkori: 'didn't start' (asosiy fe'l o'zgarilmaydi).",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 31
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "When ___ this laptop?",
    options: JSON.stringify(["she bought", "did she bought", "did she buy", "bought she"]),
    correctAnswer: "did she buy",
    explanation: "'Did' bilan so'ralganda asosiy fe'l o'zgarilmaydi: 'did she buy'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 32
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "You ___ take your shoes off in my house. You can wear them if you want.",
    options: JSON.stringify(["must", "mustn't", "have to", "don't have to"]),
    correctAnswer: "don't have to",
    explanation: "Majburiyat yo'qligi: 'don't have to'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 33
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Students ___ shout in the library.",
    options: JSON.stringify(["must", "don't have to", "mustn't", "have to"]),
    correctAnswer: "mustn't",
    explanation: "Taqiq bildirish uchun 'mustn't' ishlatiladi.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 34
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "There's ___ flag near the lake. What does it mean?",
    options: JSON.stringify(["–", "the", "two", "a"]),
    correctAnswer: "a",
    explanation: "Birinchi marta eslatilayotgan birlik ot bilan 'a' ishlatiladi.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 35
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText:
      "We watched a TV programme about languages last night. ___ programme was very interesting.",
    options: JSON.stringify(["–", "Some", "The", "A"]),
    correctAnswer: "The",
    explanation: "Oldin eslatilgan narsa uchun 'The' ishlatiladi.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 36
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Tomorrow, we ___ our friends for a coffee at 11.30 a.m.",
    options: JSON.stringify(["meeting", "meet", "met", "'re meeting"]),
    correctAnswer: "'re meeting",
    explanation: "Kelasi uchun rejalashtirilgan harakat: 'are meeting'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 37
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Martina ___ learn Spanish because she wants to go to South America.",
    options: JSON.stringify(["going to", "going", "are going to", "is going to"]),
    correctAnswer: "is going to",
    explanation: "Rejalashtirilgan niyat: 'is going to'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 38
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "What ___ do next weekend?",
    options: JSON.stringify([
      "are you going to",
      "are you going",
      "you're going to",
      "you going to",
    ]),
    correctAnswer: "are you going to",
    explanation: "So'roq gapda: 'are you going to'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 39
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "I ___ my cat to the vet this morning.",
    options: JSON.stringify(["take", "took", "taked", "was take"]),
    correctAnswer: "took",
    explanation: "'take' ning o'tgan zamoni: 'took'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 40
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Mum ___ to work, but now she walks.",
    options: JSON.stringify(["used to driving", "use to drive", "used drive", "used to drive"]),
    correctAnswer: "used to drive",
    explanation: "O'tmishdagi odatni bildirish: 'used to drive'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 41
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "My brother keeps ___ at his social media in his Geography lesson.",
    options: JSON.stringify(["to look", "that he looks", "looking", "look"]),
    correctAnswer: "looking",
    explanation: "'keeps' dan keyin gerund (-ing) keladi.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 42
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "My friends and I decided ___ out a new video game last weekend.",
    options: JSON.stringify(["checked", "check", "checking", "to check"]),
    correctAnswer: "to check",
    explanation: "'decided' dan keyin infinitiv (to + fe'l) keladi.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 43
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "This is the neighbour ___ lives in the flat under us.",
    options: JSON.stringify(["which", "where", "whose", "who"]),
    correctAnswer: "who",
    explanation: "Odamga tegishli aniqlovchi gap: 'who'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 44
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "In our local library, people ___ use computers for free, or just look at books.",
    options: JSON.stringify(["must", "can", "have to", "don't have to"]),
    correctAnswer: "can",
    explanation: "Imkoniyat/ruxsatni bildirish: 'can'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 45
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "There isn't ___ fruit. We've only got two apples.",
    options: JSON.stringify(["enough", "too", "any", "some"]),
    correctAnswer: "enough",
    explanation: "Yetarli miqdor yo'qligi: 'enough'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 46
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "The PE teacher's phone rang while we ___ weight-training.",
    options: JSON.stringify(["did", "are doing", "was doing", "were doing"]),
    correctAnswer: "were doing",
    explanation: "O'tgan davom zamoni (ko'plik): 'were doing'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 47
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "What sport ___ when he hurt his ankle last Tuesday?",
    options: JSON.stringify([
      "did Arnaud play",
      "Arnaud played",
      "was Arnaud playing",
      "Arnaud was playing",
    ]),
    correctAnswer: "was Arnaud playing",
    explanation: "O'tgan davom zamoni so'rovi: 'was Arnaud playing'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 48
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Anna will get a good mark in her Maths test if she ___ the day before.",
    options: JSON.stringify(["studies", "'s studying", "study", "'ll study"]),
    correctAnswer: "studies",
    explanation: "1-tip shart gapi: if + Present Simple → will.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 49
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Jasmina ___ Japanese food before.",
    options: JSON.stringify(["hasn't eaten", "didn't eat", "doesn't eat", "wasn't eating"]),
    correctAnswer: "hasn't eaten",
    explanation: "'before' bilan Present Perfect ishlatiladi: 'hasn't eaten'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 50
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "I've ___ visited Canada three times. It's great for hiking!",
    options: JSON.stringify(["yet", "already", "ever", "just"]),
    correctAnswer: "already",
    explanation: "Tugallangan tajriba uchun tasdiq gapda 'already' ishlatiladi.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },

  // ════════════════════════════════════════
  // VOCABULARY AND LANGUAGE FUNCTIONS (51 – 100)
  // ════════════════════════════════════════

  // 51
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "My dad's son is my ___.",
    options: JSON.stringify(["uncle", "brother", "sister", "father"]),
    correctAnswer: "brother",
    explanation: "Otangning o'g'li – sizning aka/ukangiz.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 52
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Hi! I'm from the UK. I'm ___.",
    options: JSON.stringify(["British", "United States", "American", "French"]),
    correctAnswer: "British",
    explanation: "UK fuqarosi 'British' deyiladi.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 53
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "How ___?",
    options: JSON.stringify([
      "many years have you got",
      "old are you",
      "age are you",
      "are you old",
    ]),
    correctAnswer: "old are you",
    explanation: "Yosh so'rash: 'How old are you?'",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 54
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "The ___ is on the floor in the living room.",
    options: JSON.stringify(["bath", "garden", "carpet", "wall"]),
    correctAnswer: "carpet",
    explanation: "Polda bo'ladigan narsa – 'carpet' (gilam).",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 55
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Tomo has straight blonde ___.",
    options: JSON.stringify(["arms", "eyes", "ears", "hair"]),
    correctAnswer: "hair",
    explanation: "Soch to'g'risida gap: 'hair'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 56
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Samia has got small shoes because her ___ are small.",
    options: JSON.stringify(["feet", "legs", "arms", "fingers"]),
    correctAnswer: "feet",
    explanation: "Oyoq kiyim oyoq o'lchamiga bog'liq: 'feet'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 57
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "The children ___ animals at school.",
    options: JSON.stringify(["draw", "cook", "run", "sing"]),
    correctAnswer: "draw",
    explanation: "Hayvon rasmini chizish: 'draw'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 58
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "We ___ lessons from 9.00 a.m. at school.",
    options: JSON.stringify(["get", "do", "have", "take"]),
    correctAnswer: "have",
    explanation: "Dars olish iborasi: 'have lessons'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 59
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "A: What time is it?\nB: 03.45 It's ___.",
    options: JSON.stringify([
      "forty-five past three",
      "fifteen past four",
      "quarter to four",
      "forty-five to three",
    ]),
    correctAnswer: "quarter to four",
    explanation: "03:45 = 'quarter to four' (to'rtga chorak qoldi).",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 60
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "___ are very big animals. They live in the sea.",
    options: JSON.stringify(["Frogs", "Whales", "Elephants", "Crocodiles"]),
    correctAnswer: "Whales",
    explanation: "Dengizda yashovchi eng katta hayvon – kit (whale).",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 61
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "We need two ___ for tennis. One for me and one for you.",
    options: JSON.stringify(["sticks", "nets", "bats", "rackets"]),
    correctAnswer: "rackets",
    explanation: "Tennis uchun 'racket' ishlatiladi.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 62
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "___ the weather like today?",
    options: JSON.stringify(["What does", "How does", "How is", "What is"]),
    correctAnswer: "What is",
    explanation: "Ob-havo haqida so'rash: 'What is the weather like?'",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 63
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "My cousin's mother is my ___.",
    options: JSON.stringify(["uncle", "aunt", "sister", "wife"]),
    correctAnswer: "aunt",
    explanation: "Amakivachchangizning onasi – xolangiz/ammangiz (aunt).",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 64
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "I've got a ___ today because it is hot.",
    options: JSON.stringify(["T-shirt", "jacket", "sweater", "sweatshirt"]),
    correctAnswer: "T-shirt",
    explanation: "Issiq havoda 'T-shirt' kiyiladi.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 65
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Felix can speak five languages. He's ___.",
    options: JSON.stringify(["shy", "clever", "nervous", "quiet"]),
    correctAnswer: "clever",
    explanation: "Ko'p til bilish aqlli ekanligini ko'rsatadi: 'clever'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 66
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Hi! My name's Polina. It's nice to ___ you!",
    options: JSON.stringify(["meet", "see", "find", "call"]),
    correctAnswer: "meet",
    explanation: "Tanishish iborasi: 'nice to meet you'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 67
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "I have got ___ with butter on it for my breakfast.",
    options: JSON.stringify(["lemon", "toast", "cereal", "sugar"]),
    correctAnswer: "toast",
    explanation: "Sariyog' surtilgan narsa – 'toast' (tost).",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 68
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "To cook the eggs, ___ them in water for six minutes.",
    options: JSON.stringify(["boil", "bake", "fry", "add"]),
    correctAnswer: "boil",
    explanation: "Suvda pishirish: 'boil'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 69
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "I'd ___ ketchup with my chips, please.",
    options: JSON.stringify(["would", "like", "want", "have"]),
    correctAnswer: "like",
    explanation: "'I'd like' = 'I would like' – xushmuomalalik bilan so'rash.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 70
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "I ___ a shower, eat, then go to school.",
    options: JSON.stringify(["have", "get", "wake", "go"]),
    correctAnswer: "have",
    explanation: "'Have a shower' – dush qabul qilish iborasi.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 71
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Mehmet is ___! It's his birthday, and he has got lots of presents.",
    options: JSON.stringify(["tired", "bored", "excited", "worried"]),
    correctAnswer: "excited",
    explanation: "Tug'ilgan kun sovg'alari quvontiradi: 'excited'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 72
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Daniele has got a calculator for his ___ class.",
    options: JSON.stringify(["Maths", "Music", "Art", "PE"]),
    correctAnswer: "Maths",
    explanation: "Kalkulyator matematikada ishlatiladi: 'Maths'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 73
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "I ___ school very early on Tuesdays, at 7 a.m.",
    options: JSON.stringify(["go", "start", "do", "make"]),
    correctAnswer: "start",
    explanation: "Maktabni boshlash: 'start school'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 74
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "A: Can I borrow your dictionary?\nB: Yes, ___.",
    options: JSON.stringify(["don't worry", "I'm using it", "thank you", "of course"]),
    correctAnswer: "of course",
    explanation: "Ruxsat berish: 'of course' (albatta).",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 75
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Amadi loves classical music, and she plays the violin in ___.",
    options: JSON.stringify(["a musician", "an orchestra", "an audience", "a stage"]),
    correctAnswer: "an orchestra",
    explanation: "Skripka orkestrda chalinadi: 'an orchestra'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 76
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Nothing happens in this film; it's ___. I don't know why you like it.",
    options: JSON.stringify(["alright", "brilliant", "boring", "cool"]),
    correctAnswer: "boring",
    explanation: "Hech narsa bo'lmasa – 'boring' (zerikarli).",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 77
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "___ don't we make a birthday card?",
    options: JSON.stringify(["Let's", "How", "Why", "What"]),
    correctAnswer: "Why",
    explanation: "'Why don't we…' – taklif bildirish iborasi.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 78
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "I love winter sports, and I like team games, so ___ is the sport for me.",
    options: JSON.stringify(["baseball", "basketball", "ice-skating", "ice hockey"]),
    correctAnswer: "ice hockey",
    explanation: "Qishki va jamoaviy sport: 'ice hockey'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 79
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "We ___ swimming at the weekend.",
    options: JSON.stringify(["play", "make", "do", "go"]),
    correctAnswer: "go",
    explanation: "Suzishga borish: 'go swimming'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 80
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "I wear my ___ when I want to listen to music.",
    options: JSON.stringify(["computer", "screen", "printer", "headphones"]),
    correctAnswer: "headphones",
    explanation: "Musiqa tinglash uchun quloqchin: 'headphones'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 81
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "I need to speak to my mum. Can I ___ a call, please?",
    options: JSON.stringify(["get", "use", "make", "text"]),
    correctAnswer: "make",
    explanation: "Qo'ng'iroq qilish: 'make a call'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 82
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "A: Smartphones are useful!\nB: ___ true.",
    options: JSON.stringify(["You're", "That's", "This", "I think so"]),
    correctAnswer: "That's",
    explanation: "Fikrga rozi bo'lish: 'That's true'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 83
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "We live in a small ___.",
    options: JSON.stringify(["village", "capital city", "island", "lake"]),
    correctAnswer: "village",
    explanation: "Kichik yashash joyi: 'village' (qishloq).",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 84
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Let's go ___ in the mountains!",
    options: JSON.stringify(["shopping", "surfing", "hiking", "sightseeing"]),
    correctAnswer: "hiking",
    explanation: "Tog'da yurishga borish: 'go hiking'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 85
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "We have to wait at this bus ___ for the number 11 bus.",
    options: JSON.stringify(["park", "lane", "metro", "stop"]),
    correctAnswer: "stop",
    explanation: "Avtobus bekati: 'bus stop'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 86
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "I'm driving slowly today because it's ___, so it isn't easy to see.",
    options: JSON.stringify(["cloudy", "windy", "foggy", "warm"]),
    correctAnswer: "foggy",
    explanation: "Ko'rishni qiyinlashtiradigan ob-havo: 'foggy' (tumanli).",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 87
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "A: How do I get to the train station, please?\nB: Go ___ on. It's not far.",
    options: JSON.stringify(["turning", "next", "straight", "near"]),
    correctAnswer: "straight",
    explanation: "To'g'ri yo'nalish: 'go straight on'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 88
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Olivia, I know you like ___. Can you be in a short film we're making?",
    options: JSON.stringify(["playing", "acting", "taking", "watching"]),
    correctAnswer: "acting",
    explanation: "Film aktrisasi bo'lish: 'acting'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 89
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText:
      "Thulani wants to understand today's world better, so he watches ___ on TV.",
    options: JSON.stringify(["reality shows", "current affairs", "soap operas", "talent shows"]),
    correctAnswer: "current affairs",
    explanation: "Dunyoni tushunish uchun yangiliklar ko'rish: 'current affairs'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 90
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "I like walking my dog because it's ___.",
    options: JSON.stringify(["relaxing", "relaxation", "relax", "relaxed"]),
    correctAnswer: "relaxing",
    explanation: "Holatni tasvirlovchi sifat: 'relaxing'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 91
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Can I ___ my phone, please? The battery died.",
    options: JSON.stringify(["join", "charge", "check", "send"]),
    correctAnswer: "charge",
    explanation: "Telefon zaryadlash: 'charge'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 92
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Please put the cups and plates in the ___ after dinner.",
    options: JSON.stringify(["fridge", "washing machine", "microwave", "dishwasher"]),
    correctAnswer: "dishwasher",
    explanation: "Idish yuvish mashinasi: 'dishwasher'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 93
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "When you ___ your bed, can you collect your clothes for washing too?",
    options: JSON.stringify(["do", "make", "put", "tidy"]),
    correctAnswer: "make",
    explanation: "To'shak yig'ish: 'make your bed'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 94
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Hue ___ her hand on a hot part of the cooker today, but she's OK.",
    options: JSON.stringify(["burned", "broke", "cut", "hit"]),
    correctAnswer: "burned",
    explanation: "Issiq narsaga tegib kuyish: 'burned'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 95
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "What's ___ with you? Do you need a doctor?",
    options: JSON.stringify(["matter", "problem", "wrong", "hurt"]),
    correctAnswer: "wrong",
    explanation: "Muammo so'rash: 'What's wrong with you?'",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 96
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Can you get some tomatoes at the ___?",
    options: JSON.stringify(["bakery", "greengrocer's", "florist's", "butcher's"]),
    correctAnswer: "greengrocer's",
    explanation: "Sabzavot do'koni: 'greengrocer's'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 97
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "These jeans are in ___, so they are cheaper at the moment.",
    options: JSON.stringify(["a bigger size", "another colour", "the sale", "the changing rooms"]),
    correctAnswer: "the sale",
    explanation: "Chegirmali sotuv: 'the sale'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 98
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "My dad is ___, so he's really good with numbers!",
    options: JSON.stringify(["an artist", "an accountant", "a chef", "a tour guide"]),
    correctAnswer: "an accountant",
    explanation: "Raqamlar bilan ishlash – buxgalter: 'accountant'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 99
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "This weekend, we want to go ___ on a river.",
    options: JSON.stringify(["hiking", "cycling", "kayaking", "snowboarding"]),
    correctAnswer: "kayaking",
    explanation: "Daryoda qayiqda suzish: 'kayaking'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 100
  {
    testId: TEST_ID,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText:
      "I know a good way to the beach, down between those high ___.",
    options: JSON.stringify(["valleys", "cliffs", "islands", "coasts"]),
    correctAnswer: "cliffs",
    explanation: "Sohil bo'yidagi baland qoyalar: 'cliffs'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
];

// ════════════════════════════════════════════════════════════
// B VARIANT SAVOLLARI  (testId = 2)
// ════════════════════════════════════════════════════════════

const TEST_ID_B = 2;

export const questionsB = [
  // ════════════════════════════════════════
  // GRAMMAR  (1 – 50)
  // ════════════════════════════════════════

  // 1
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "I ___ thirteen years old.",
    options: JSON.stringify(["am", "are", "is", "have"]),
    correctAnswer: "am",
    explanation: "'I' bilan 'am' ishlatiladi.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 2
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "My uncle ___ British.",
    options: JSON.stringify(["has not", "is not", "are not", "am not"]),
    correctAnswer: "is not",
    explanation: "'Uncle' birlik (he), shuning uchun 'is not' to'g'ri.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 3
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Look at ___ T-shirt over there.",
    options: JSON.stringify(["those", "this", "that", "these"]),
    correctAnswer: "that",
    explanation: "'Over there' uzoqdagi birlikni ko'rsatadi: 'that'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 4
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "There ___ a table in the kitchen.",
    options: JSON.stringify(["is", "be", "has", "are"]),
    correctAnswer: "is",
    explanation: "'A table' birlik, shuning uchun 'is' to'g'ri.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 5
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "They ___ brown eyes.",
    options: JSON.stringify(["has", "have got", "has got", "got"]),
    correctAnswer: "have got",
    explanation: "'They' ko'plik, shuning uchun 'have got' ishlatiladi.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 6
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "___ you got wavy hair?",
    options: JSON.stringify(["Is", "Do", "Has", "Have"]),
    correctAnswer: "Have",
    explanation: "'You' bilan 'Have' ishlatiladi.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 7
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Julian ___ read.",
    options: JSON.stringify(["isn't", "hasn't", "can't", "not"]),
    correctAnswer: "can't",
    explanation: "Qobiliyat inkorini bildirish uchun 'can't' ishlatiladi.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 8
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "___ Sofia cook?",
    options: JSON.stringify(["Has", "Is", "Can", "Have"]),
    correctAnswer: "Can",
    explanation: "Qobiliyat so'rovi uchun 'Can' ishlatiladi.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 9
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Dad ___ to music in the evening.",
    options: JSON.stringify(["listening", "listens", "listened", "listen"]),
    correctAnswer: "listens",
    explanation: "3-shaxs birlik (he/she/it) uchun fe'lga -s qo'shiladi.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 10
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Bartek ___ want a dog.",
    options: JSON.stringify(["has not", "have not", "does not", "do not"]),
    correctAnswer: "does not",
    explanation: "3-shaxs birlik inkori: 'does not'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 11
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "___ frogs live in trees?",
    options: JSON.stringify(["Do", "Are", "Does", "Is"]),
    correctAnswer: "Do",
    explanation: "'Frogs' ko'plik, shuning uchun 'Do' ishlatiladi.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 12
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Julia loves ___ football.",
    options: JSON.stringify(["played", "play", "plays", "playing"]),
    correctAnswer: "playing",
    explanation: "'loves' dan keyin gerund (-ing) keladi.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 13
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "___ can you see?",
    options: JSON.stringify(["What", "Whose", "When", "Where"]),
    correctAnswer: "What",
    explanation: "Ko'rgan narsani so'rash uchun 'What' ishlatiladi.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 14
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "I'm looking for Martina. I think this is ___ notebook.",
    options: JSON.stringify(["she", "her", "she's", "his"]),
    correctAnswer: "her",
    explanation: "Egalik olmoshi: ayol uchun 'her'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 15
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "There isn't ___ sugar.",
    options: JSON.stringify(["a", "the", "any", "some"]),
    correctAnswer: "any",
    explanation: "Inkor gapda sanalmaydigan ot bilan 'any' ishlatiladi.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 16
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "How ___ milk have you got?",
    options: JSON.stringify(["any", "many", "some", "much"]),
    correctAnswer: "much",
    explanation: "Sanalmaydigan ot bilan 'much' ishlatiladi.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 17
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "There are ___ bananas in the kitchen.",
    options: JSON.stringify(["any", "a", "some", "much"]),
    correctAnswer: "some",
    explanation: "Tasdiq gapda ko'plik bilan 'some' ishlatiladi.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 18
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "When ___ Sofia have lunch?",
    options: JSON.stringify(["has", "do", "does", "is"]),
    correctAnswer: "does",
    explanation: "3-shaxs birlik so'rovi uchun 'does' ishlatiladi.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 19
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "The children ___ in the classroom now.",
    options: JSON.stringify(["are talking", "is talk", "are talk", "is talking"]),
    correctAnswer: "are talking",
    explanation: "Hozirgi davom zamoni (ko'plik): 'are talking'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 20
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Filip ___ doing anything now.",
    options: JSON.stringify(["don't", "isn't", "am not", "aren't"]),
    correctAnswer: "isn't",
    explanation: "'Filip' birlik, hozirgi davom zamoni inkori: 'isn't'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 21
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "My friends usually ___ to a film club at the weekend.",
    options: JSON.stringify(["go", "going", "are going", "goes"]),
    correctAnswer: "go",
    explanation: "'Usually' odatiy harakatni bildiradi; ko'plik: 'go'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 22
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "We ___ our homework at the moment.",
    options: JSON.stringify(["'re doing", "do", "doing", "does"]),
    correctAnswer: "'re doing",
    explanation: "Hozirgi davom zamoni: 'We're doing'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 23
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Pop music is ___ than hip-hop.",
    options: JSON.stringify(["very nice", "nicer", "nice", "more nice"]),
    correctAnswer: "nicer",
    explanation: "Qisqa sifat bilan qiyosiy daraja: 'nicer'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 24
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Some people think the violin is ___ instrument to play.",
    options: JSON.stringify([
      "the difficult",
      "more difficult",
      "the more difficult",
      "the most difficult",
    ]),
    correctAnswer: "the most difficult",
    explanation: "Ustunlik darajasi: 'the most difficult'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 25
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Classical music is ___ music. I love it.",
    options: JSON.stringify(["better", "the best", "the better", "the good"]),
    correctAnswer: "the best",
    explanation: "Ustunlik darajasi: 'the best'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 26
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "___ your friends at the swimming pool last week?",
    options: JSON.stringify(["Were", "Are", "Is", "Was"]),
    correctAnswer: "Were",
    explanation: "'Friends' ko'plik, o'tgan zamon: 'Were'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 27
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "There ___ a lot of people at the school sports day.",
    options: JSON.stringify(["was", "came", "were", "had"]),
    correctAnswer: "were",
    explanation: "'A lot of people' ko'plik, o'tgan zamon: 'were'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 28
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "We ___ tennis last week.",
    options: JSON.stringify(["playing", "played", "play", "plays"]),
    correctAnswer: "played",
    explanation: "O'tgan oddiy zamon: 'played'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 29
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Alejandra ___ her tennis competition last week.",
    options: JSON.stringify(["winning", "wins", "won", "winned"]),
    correctAnswer: "won",
    explanation: "'win' ning o'tgan zamoni: 'won'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 30
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "People ___ video games in the nineteenth century.",
    options: JSON.stringify(["not play", "don't play", "aren't playing", "didn't play"]),
    correctAnswer: "didn't play",
    explanation: "O'tgan zamon inkori: 'didn't play'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 31
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Where ___ this selfie?",
    options: JSON.stringify(["did she take", "she took", "she did take", "took she"]),
    correctAnswer: "did she take",
    explanation: "'Did' bilan so'ralganda asosiy fe'l o'zgarilmaydi: 'did she take'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 32
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "You ___ talk during the test.",
    options: JSON.stringify(["mustn't", "don't have to", "have to", "must"]),
    correctAnswer: "mustn't",
    explanation: "Taqiq bildirish uchun 'mustn't' ishlatiladi.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 33
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText:
      "Students ___ write this part of the test in pencil. They can use a pen.",
    options: JSON.stringify(["don't have to", "must", "mustn't", "have to"]),
    correctAnswer: "don't have to",
    explanation: "Majburiyat yo'qligi: 'don't have to'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 34
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "There's ___ flag near the lake. What does it mean?",
    options: JSON.stringify(["–", "a", "two", "the"]),
    correctAnswer: "a",
    explanation: "Birinchi marta eslatilayotgan birlik ot bilan 'a' ishlatiladi.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 35
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText:
      "We watched a TV programme about languages last night. ___ programme was very interesting.",
    options: JSON.stringify(["–", "Some", "The", "A"]),
    correctAnswer: "The",
    explanation: "Oldin eslatilgan narsa uchun 'The' ishlatiladi.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 36
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Tomorrow, I ___ a friend for a coffee at 11.00 a.m.",
    options: JSON.stringify(["will meet", "meet", "met", "'m meeting"]),
    correctAnswer: "'m meeting",
    explanation: "Kelasi uchun rejalashtirilgan harakat: 'I'm meeting'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 37
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Adam and his brother ___ camp in the forest next weekend.",
    options: JSON.stringify(["are going to", "going", "are going", "going to"]),
    correctAnswer: "are going to",
    explanation: "Rejalashtirilgan niyat: 'are going to'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 38
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "What ___ do next summer?",
    options: JSON.stringify([
      "we're going to",
      "we going to",
      "are we going to",
      "are going to",
    ]),
    correctAnswer: "are we going to",
    explanation: "So'roq gapda: 'are we going to'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 39
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "My brother ___ a football match last week.",
    options: JSON.stringify(["losed", "lost", "lose", "did lose"]),
    correctAnswer: "lost",
    explanation: "'lose' ning o'tgan zamoni: 'lost'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 40
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Tine ___ photos with a camera, but now he uses his phone.",
    options: JSON.stringify(["used to taking", "use to take", "used take", "used to take"]),
    correctAnswer: "used to take",
    explanation: "O'tmishdagi odatni bildirish: 'used to take'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 41
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "My brother keeps ___ at his social media in his Geography lesson.",
    options: JSON.stringify(["to look", "that he looks", "look", "looking"]),
    correctAnswer: "looking",
    explanation: "'keeps' dan keyin gerund (-ing) keladi.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 42
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "I agreed ___ my friend how to use a really good language app.",
    options: JSON.stringify(["to teach", "teaching", "that I teach", "teach"]),
    correctAnswer: "to teach",
    explanation: "'agreed' dan keyin infinitiv (to + fe'l) keladi.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 43
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "This is the vacuum cleaner ___ doesn't make any noise.",
    options: JSON.stringify(["which", "where", "whose", "who"]),
    correctAnswer: "which",
    explanation: "Narsaga tegishli aniqlovchi gap: 'which'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 44
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "In our local library, people ___ use computers for free, or just look at books.",
    options: JSON.stringify(["don't have to", "must", "have to", "can"]),
    correctAnswer: "can",
    explanation: "Imkoniyat/ruxsatni bildirish: 'can'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 45
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "There aren't ___ vegetables for dinner, only two carrots. Let's go shopping!",
    options: JSON.stringify(["any", "too", "enough", "some"]),
    correctAnswer: "enough",
    explanation: "Yetarli miqdor yo'qligi: 'enough'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 46
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "I got very tired today while I ___ basketball.",
    options: JSON.stringify(["playing", "was playing", "were playing", "am playing"]),
    correctAnswer: "was playing",
    explanation: "O'tgan davom zamoni (birlik): 'was playing'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 47
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "What sport ___ when he hurt his ankle last Tuesday?",
    options: JSON.stringify([
      "did Hans play",
      "Hans played",
      "Hans was playing",
      "was Hans playing",
    ]),
    correctAnswer: "was Hans playing",
    explanation: "O'tgan davom zamoni so'rovi: 'was Hans playing'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 48
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Alenka will get a good mark in her Maths test if she ___ the day before.",
    options: JSON.stringify(["study", "'s studying", "studies", "'ll study"]),
    correctAnswer: "studies",
    explanation: "1-tip shart gapi: if + Present Simple → will.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 49
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Roberto ___ in a river before.",
    options: JSON.stringify(["wasn't swimming", "didn't swim", "doesn't swim", "hasn't swum"]),
    correctAnswer: "hasn't swum",
    explanation: "'before' bilan Present Perfect ishlatiladi: 'hasn't swum'.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },
  // 50
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "I've ___ visited Canada three times. It's great for hiking!",
    options: JSON.stringify(["already", "yet", "still", "just"]),
    correctAnswer: "already",
    explanation: "Tugallangan tajriba uchun tasdiq gapda 'already' ishlatiladi.",
    points: 1,
    difficulty: 1,
    skill: "Grammar",
    isActive: true,
  },

  // ════════════════════════════════════════
  // VOCABULARY AND LANGUAGE FUNCTIONS (51 – 100)
  // ════════════════════════════════════════

  // 51
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "My dad's daughter is my ___.",
    options: JSON.stringify(["mother", "aunt", "brother", "sister"]),
    correctAnswer: "sister",
    explanation: "Otangning qizi – sizning opa/singlizingiz.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 52
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Hi! I am from the USA. I am ___.",
    options: JSON.stringify(["English", "United States", "American", "German"]),
    correctAnswer: "American",
    explanation: "USA fuqarosi 'American' deyiladi.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 53
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "How ___?",
    options: JSON.stringify([
      "many years do you have",
      "age are you",
      "old are you",
      "years you have",
    ]),
    correctAnswer: "old are you",
    explanation: "Yosh so'rash: 'How old are you?'",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 54
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "There is a big fridge in my ___.",
    options: JSON.stringify(["bedroom", "kitchen", "bathroom", "living room"]),
    correctAnswer: "kitchen",
    explanation: "Muzlatkich oshxonada bo'ladi: 'kitchen'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 55
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Veronica has curly brown ___.",
    options: JSON.stringify(["hair", "eyes", "ears", "arms"]),
    correctAnswer: "hair",
    explanation: "Soch to'g'risida gap: 'hair'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 56
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Irene has got small shoes because her ___ are small.",
    options: JSON.stringify(["fingers", "legs", "arms", "feet"]),
    correctAnswer: "feet",
    explanation: "Oyoq kiyim oyoq o'lchamiga bog'liq: 'feet'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 57
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "I ___ a book every day.",
    options: JSON.stringify(["draw", "read", "run", "act"]),
    correctAnswer: "read",
    explanation: "Kitob o'qish: 'read'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 58
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "I ___ my homework after dinner.",
    options: JSON.stringify(["do", "get", "have", "go"]),
    correctAnswer: "do",
    explanation: "Uy vazifasini bajarish: 'do homework'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 59
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "A: What time is it?\nB: 05.45 It's ___.",
    options: JSON.stringify([
      "forty-five past five",
      "quarter to six",
      "fifteen past six",
      "forty-five to five",
    ]),
    correctAnswer: "quarter to six",
    explanation: "05:45 = 'quarter to six' (oltiga chorak qoldi).",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 60
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "___ spend a lot of time in trees.",
    options: JSON.stringify(["Elephants", "Whales", "Monkeys", "Kangaroos"]),
    correctAnswer: "Monkeys",
    explanation: "Daraxtda yashovchi hayvon – maymun (monkey).",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 61
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "I have got ___ when I swim.",
    options: JSON.stringify(["goggles", "nets", "sticks", "helmets"]),
    correctAnswer: "goggles",
    explanation: "Suzishda ko'z himoyasi uchun 'goggles' ishlatiladi.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 62
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "___ the weather like today?",
    options: JSON.stringify(["What does", "How does", "What is", "How is"]),
    correctAnswer: "What is",
    explanation: "Ob-havo haqida so'rash: 'What is the weather like?'",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 63
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "My cousin's dad is my ___.",
    options: JSON.stringify(["brother", "aunt", "husband", "uncle"]),
    correctAnswer: "uncle",
    explanation: "Amakivachchangizning otasi – amangiz (uncle).",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 64
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "I've got a ___ today because it's cold.",
    options: JSON.stringify(["jacket", "dress", "skirt", "T-shirt"]),
    correctAnswer: "jacket",
    explanation: "Sovuq havoda 'jacket' kiyiladi.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 65
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Fernanda can speak five languages. She's ___.",
    options: JSON.stringify(["shy", "quiet", "nervous", "clever"]),
    correctAnswer: "clever",
    explanation: "Ko'p til bilish aqlli ekanligini ko'rsatadi: 'clever'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 66
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Hi! My name's Mario. It's ___ to meet you!",
    options: JSON.stringify(["fine", "nice", "well", "happy"]),
    correctAnswer: "nice",
    explanation: "Tanishish iborasi: 'nice to meet you'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 67
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "I have got cereal with ___ for my breakfast.",
    options: JSON.stringify(["mushrooms", "milk", "rice", "eggs"]),
    correctAnswer: "milk",
    explanation: "Nonushta uchun g'alla sut bilan: 'milk'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 68
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "We need to ___ this cake at 180°C for thirty-five minutes.",
    options: JSON.stringify(["bake", "mix", "fry", "boil"]),
    correctAnswer: "bake",
    explanation: "Pecda pishirish: 'bake'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 69
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "I'd ___ ketchup with my chips, please.",
    options: JSON.stringify(["would", "want", "like", "have"]),
    correctAnswer: "like",
    explanation: "'I'd like' = 'I would like' – xushmuomalalik bilan so'rash.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 70
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Gabriela ___ dressed, then has breakfast.",
    options: JSON.stringify(["gets", "wakes", "goes", "has"]),
    correctAnswer: "gets",
    explanation: "Kiyinish iborasi: 'gets dressed'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 71
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Michal is ___! It's his birthday, and he has got lots of presents.",
    options: JSON.stringify(["tired", "excited", "bored", "worried"]),
    correctAnswer: "excited",
    explanation: "Tug'ilgan kun sovg'alari quvontiradi: 'excited'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 72
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Barbara has got a dictionary for her ___ class.",
    options: JSON.stringify(["Music", "PE", "Maths", "English"]),
    correctAnswer: "English",
    explanation: "Lug'at ingliz tili darsida ishlatiladi: 'English'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 73
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "I ___ school very early on Tuesdays, at 7 a.m.",
    options: JSON.stringify(["do", "make", "start", "go"]),
    correctAnswer: "start",
    explanation: "Maktabni boshlash: 'start school'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 74
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "A: Can I use your laptop?\nB: ___, you can't.",
    options: JSON.stringify(["Of course", "Sorry", "No, thank you", "No problem"]),
    correctAnswer: "Sorry",
    explanation: "Rad etish bilan uzr so'rash: 'Sorry'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 75
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Marushka enjoys rock, and she plays the drums in ___.",
    options: JSON.stringify(["an orchestra", "an audience", "a musician", "a band"]),
    correctAnswer: "a band",
    explanation: "Rok musiqa guruhida: 'a band'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 76
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "That song is ___! Please never play it again.",
    options: JSON.stringify(["fantastic", "alright", "terrible", "hard"]),
    correctAnswer: "terrible",
    explanation: "Yomon narsa – 'terrible' (dahshatli).",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 77
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "A: Why don't we go to the folk music concert?\nB: I'm not sure ___ a good idea.",
    options: JSON.stringify(["of course", "that's", "maybe", "it has"]),
    correctAnswer: "that's",
    explanation: "Fikrga shubha: 'that's a good idea'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 78
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "I love winter sports, and I like team games, so ___ is the sport for me.",
    options: JSON.stringify(["ice hockey", "basketball", "ice-skating", "baseball"]),
    correctAnswer: "ice hockey",
    explanation: "Qishki va jamoaviy sport: 'ice hockey'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 79
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Virginie ___ judo at the weekend.",
    options: JSON.stringify(["plays", "makes", "does", "goes"]),
    correctAnswer: "does",
    explanation: "Judo bilan shug'ullanish: 'does judo'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 80
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "The ___ on my laptop is big. I watch films on it.",
    options: JSON.stringify(["tablet", "screen", "smartphone", "printer"]),
    correctAnswer: "screen",
    explanation: "Filmlar ko'rish uchun ekran: 'screen'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 81
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "My smartphone ___ my steps when I'm walking.",
    options: JSON.stringify(["makes", "gets", "takes", "counts"]),
    correctAnswer: "counts",
    explanation: "Qadamlarni hisoblash: 'counts'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 82
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "A: Games consoles are great!\nB: You ___.",
    options: JSON.stringify(["are right", "have right", "have true", "are true"]),
    correctAnswer: "are right",
    explanation: "Fikrga rozi bo'lish: 'You are right'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 83
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "The ___ of England is London.",
    options: JSON.stringify(["language", "village", "city", "capital"]),
    correctAnswer: "capital",
    explanation: "Poytaxt: 'capital'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 84
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "It's sunny today and I want to relax. Let's go ___!",
    options: JSON.stringify(["hiking", "surfing", "sunbathing", "sightseeing"]),
    correctAnswer: "sunbathing",
    explanation: "Quyoshda yotish: 'sunbathing'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 85
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "It's easy to ride our bikes to the city centre because there are cycle ___.",
    options: JSON.stringify(["stops", "lanes", "stations", "parks"]),
    correctAnswer: "lanes",
    explanation: "Velosiped yo'llari: 'cycle lanes'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 86
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "It's ___ today, so you need to go to school with an umbrella.",
    options: JSON.stringify(["foggy", "cloudy", "rainy", "sunny"]),
    correctAnswer: "rainy",
    explanation: "Soyabon kerak bo'lsa – 'rainy' (yomg'irli).",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 87
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText:
      "A: How do I get to the bus station, please?\nB: Go to end of this street. You can't ___ it.",
    options: JSON.stringify(["lose", "turn", "miss", "take"]),
    correctAnswer: "miss",
    explanation: "Ko'rib qolmaslik: 'you can't miss it'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 88
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Hubert ___ a lot of selfies on his phone.",
    options: JSON.stringify(["starts", "does", "makes", "takes"]),
    correctAnswer: "takes",
    explanation: "Selfie olish: 'takes selfies'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 89
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText:
      "Kiet's favourite TV programme is a ___ show: the audience chooses the best dancer.",
    options: JSON.stringify(["reality", "talent", "talk", "game"]),
    correctAnswer: "talent",
    explanation: "Eng yaxshi raqschiini tomoshabinlar tanlaydigan ko'rsatuv: 'talent show'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 90
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText:
      "Ines felt ___ in yesterday's Maths lesson because she didn't know the answer.",
    options: JSON.stringify(["embarrass", "embarrasses", "embarrassed", "embarrassing"]),
    correctAnswer: "embarrassed",
    explanation: "His-tuyg'uni ifodalovchi sifat: 'embarrassed'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 91
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "I think we need to leave soon. Let me ___ the time on my phone.",
    options: JSON.stringify(["take", "charge", "check", "look for"]),
    correctAnswer: "check",
    explanation: "Vaqtni tekshirish: 'check the time'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 92
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "We need another ___ for all our clothes.",
    options: JSON.stringify(["hall", "bedside table", "rug", "wardrobe"]),
    correctAnswer: "wardrobe",
    explanation: "Kiyimlar uchun shkaf: 'wardrobe'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 93
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "After washing the dishes, can you ___ them and put them away?",
    options: JSON.stringify(["vacuum", "clean", "dry", "tidy"]),
    correctAnswer: "dry",
    explanation: "Idishlarni artish: 'dry'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 94
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "Kai stood up too quickly and ___ his head on a cupboard.",
    options: JSON.stringify(["burned", "broke", "hit", "cut"]),
    correctAnswer: "hit",
    explanation: "Boshini narsaga urish: 'hit'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 95
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "You've got a ___ temperature. You need a doctor.",
    options: JSON.stringify(["strong", "high", "big", "hot"]),
    correctAnswer: "high",
    explanation: "Yuqori harorat: 'high temperature'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 96
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "We need some bread. Let's find a ___.",
    options: JSON.stringify(["bakery", "newsagent", "butcher", "florist's"]),
    correctAnswer: "bakery",
    explanation: "Non do'koni: 'bakery'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 97
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "This shirt is too small. ___",
    options: JSON.stringify([
      "I'll take it.",
      "I'm looking for the changing rooms.",
      "Can I try it on?",
      "Have you got it in a bigger size?",
    ]),
    correctAnswer: "Have you got it in a bigger size?",
    explanation: "Kattaroq o'lcham so'rash: 'Have you got it in a bigger size?'",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 98
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "A great ___ works here, so the food is expensive but really good!",
    options: JSON.stringify(["waiter", "accountant", "chef", "lawyer"]),
    correctAnswer: "chef",
    explanation: "Oshpaz: 'chef'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 99
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "You should always wear a ___ when you go mountain biking.",
    options: JSON.stringify(["helmet", "life jacket", "paddle", "wetsuit"]),
    correctAnswer: "helmet",
    explanation: "Bosh himoyasi uchun: 'helmet'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
  // 100
  {
    testId: TEST_ID_B,
    type: "MCQ",
    inputType: "OPTIONS",
    questionText: "I know a good way to the beach, down between those high ___.",
    options: JSON.stringify(["valleys", "coasts", "islands", "cliffs"]),
    correctAnswer: "cliffs",
    explanation: "Sohil bo'yidagi baland qoyalar: 'cliffs'.",
    points: 1,
    difficulty: 1,
    skill: "Vocabulary",
    isActive: true,
  },
];
