// Pre-intermediate placement test: Wider World Second Edition Level 3.
// testId = 3 -> A variant savollari
const TEST_ID_A = 3;

// testId = 4 -> B variant savollari
const TEST_ID_B = 4;

export const questionsA = [
  // 1
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'Martha ___ like fantasy films. She prefers action films.',
    options: ['do', "don't", 'does', "doesn't"],
    correctAnswer: "doesn't",
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 2
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'A: Where ___ come from?\nB: They come from Germany.',
    options: ['do they', 'they', 'are they', 'does they'],
    correctAnswer: 'do they',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 3
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'I ___ a tracksuit at the moment.',
    options: ['wear', 'wears', "'m wearing", "'s wearing"],
    correctAnswer: "'m wearing",
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 4
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: '___ the blue bird in the garden yesterday?',
    options: ['Were', 'Was', 'Is', 'Are'],
    correctAnswer: 'Was',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 5
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText:
      'We ___ make films with video cameras, now we make them with our phones.',
    options: ['used to', 'used', 'use to', 'use'],
    correctAnswer: 'used to',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 6
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'Steven enjoys ___ games on his phone.',
    options: ['play', 'to play', 'to playing', 'playing'],
    correctAnswer: 'playing',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 7
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: "This is the restaurant ___ where we'll have dinner.",
    options: ['who', 'which', 'where', 'that'],
    correctAnswer: 'where',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 8
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: '___ to go to bed early tonight?',
    options: ['Do we have', 'Can we', 'Must we', 'Have we'],
    correctAnswer: 'Do we have',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 9
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'These shoes are ___ than those ones.',
    options: ['expensive', 'as expensive', 'most expensive', 'more expensive'],
    correctAnswer: 'more expensive',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 10
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: '___ work from home in the future?',
    options: [
      'All people will',
      'Do all people',
      'Will all people',
      'All people',
    ],
    correctAnswer: 'Will all people',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 11
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: "If you ___ study, you won't get a good mark in the test.",
    options: ["won't", "don't", 'do', 'will'],
    correctAnswer: "don't",
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 12
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'My parents ___ visited more than twenty countries.',
    options: ["haven't", "hasn't", "didn't", "won't"],
    correctAnswer: "haven't",
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 13
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'My sister ___ selfies. She hates them.',
    options: [
      'never takes',
      'is never taking',
      'are never taking',
      'never take',
    ],
    correctAnswer: 'never takes',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 14
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: "To stay safe, avoid ___ people you don't know to the group.",
    options: ['add', 'to add', 'to adding', 'adding'],
    correctAnswer: 'adding',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 15
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'Are you planning ___ a smart speaker soon?',
    options: ['buy', 'buying', 'to buy', 'to buying'],
    correctAnswer: 'to buy',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 16
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: "I didn't ___ it rained last night.",
    options: ['know', 'knew', 'knowing', 'known'],
    correctAnswer: 'know',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 17
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'What were you doing when the storm ___?',
    options: ['were starting', 'started', 'starts', 'has started'],
    correctAnswer: 'started',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 18
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: "I haven't fried the sausages___.",
    options: ['yet', 'ever', 'just', 'never'],
    correctAnswer: 'yet',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 19
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: "I've known this recipe ___ a long time.",
    options: ['ever', 'for', 'yet', 'since'],
    correctAnswer: 'for',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 20
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: '___ you ever eaten a mango?',
    options: ['Has', 'Are', 'Have', 'Did'],
    correctAnswer: 'Have',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 21
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: "This film is ___ boring to watch. Let's change it.",
    options: ['enough', 'too', 'more', 'the most'],
    correctAnswer: 'too',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 22
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: "Dramas aren't as ___ documentaries, in my opinion.",
    options: [
      'interesting',
      'interesting than',
      'interesting as',
      'more interesting',
    ],
    correctAnswer: 'interesting as',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 23
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: "There weren't ___ people in the theatre last night.",
    options: ['many', 'much', 'lots', 'some'],
    correctAnswer: 'many',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 24
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText:
      "You need very ___ money to make a short film. It's not very expensive.",
    options: ['lots', 'a few', 'much', 'little'],
    correctAnswer: 'little',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 25
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText:
      '___ join a gym this year? Or are you planning another type of exercise?',
    options: ['Are you going to', 'Will you go', 'Do you', 'Are you going'],
    correctAnswer: 'Are you going to',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 26
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: "You won't become good at karate unless you ___ a lot.",
    options: ["don't practise", 'practise', 'will practise', "won't practise"],
    correctAnswer: 'practise',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 27
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'You ___ to book the hotel early as it gets busy.',
    options: ['must', 'should', 'ought', 'has'],
    correctAnswer: 'ought',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 28
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: "We ___ stay on a campsite if you don't want to.",
    options: ["don't have to", 'should', 'ought to', "mustn't"],
    correctAnswer: "don't have to",
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 29
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText:
      'The guidebook says the museum is here, but that ___ be right, this is a shop!',
    options: ['must', 'could', 'might', "can't"],
    correctAnswer: "can't",
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 30
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: "If I ___ more time, I'd spend it with my family.",
    options: ['have', 'would have', 'had', 'was having'],
    correctAnswer: 'had',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 31
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'If I were you, I ___ to your friend like that.',
    options: ["won't speak", "wouldn't speak", 'not speak', 'speak'],
    correctAnswer: "wouldn't speak",
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 32
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'Adam, ___ lives next door to me, is my best friend.',
    options: ['who', 'that', 'which', 'where'],
    correctAnswer: 'who',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 33
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'Hundreds of crime novels ___ every year.',
    options: ['is written', 'write', 'are written', 'written'],
    correctAnswer: 'are written',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 34
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'The bank robbers ___ by the police yesterday.',
    options: ['was arrested', 'are arrested', 'arrested', 'were arrested'],
    correctAnswer: 'were arrested',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 35
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'After the burglary, my parents ___.',
    options: [
      'had the windows changed',
      'had changed the windows',
      'the windows had changed',
      'the windows changed',
    ],
    correctAnswer: 'had the windows changed',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 36
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'Imogen said she ___ for a new after-school club to join.',
    options: ['looks', 'was looking', 'has looked', 'looked'],
    correctAnswer: 'was looking',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 37
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText:
      'A: Who ___ you Maths last year?\nB: Mr Dorton. He was a great teacher.',
    options: ['did teach', 'did you teach', 'taught', 'you taught'],
    correctAnswer: 'taught',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 38
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'When I got up, my dad ___ thrown away the rubbish.',
    options: ['had already', 'has already', 'was already', 'already had'],
    correctAnswer: 'had already',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 39
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'Did you ___ to your teacher yesterday?',
    options: ['spoke', 'use to speak', 'used to speak', 'speak'],
    correctAnswer: 'speak',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 40
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: '___ have you been recycling plastic at home?',
    options: ['How often', 'How long', 'How old', 'How many'],
    correctAnswer: 'How long',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 41
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText:
      'Sara has ___ three phone cases for people in her family this weekend.',
    options: ['been making', 'been made', 'made', 'making'],
    correctAnswer: 'made',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 42
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: "In ten years' time, I'll ___ as a mechanic, I hope!",
    options: ['be working', 'be work', 'work', 'working'],
    correctAnswer: 'be working',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 43
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText:
      "When satellites first ___ Earth's atmosphere, they get very hot.",
    options: ['would enter', 'entered', 'will enter', 'enter'],
    correctAnswer: 'enter',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 44
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: "If they hadn't used the telescope, they ___ the comet.",
    options: [
      "wouldn't have seen",
      'would have seen',
      'would see',
      "wouldn't see",
    ],
    correctAnswer: "wouldn't have seen",
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 45
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'The doctor asked me if ___.',
    options: [
      'was my arm hurting',
      'was hurting my arm',
      'my arm was hurting',
      'is hurting my arm',
    ],
    correctAnswer: 'my arm was hurting',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 46
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'The doctor told me ___ so much fast food.',
    options: ['not to eat', 'not eat', 'to eat not', "don't eat"],
    correctAnswer: 'not to eat',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 47
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText:
      'The course will ___ by a person with great communication skills.',
    options: ['teach', 'taught', 'be teaching', 'be taught'],
    correctAnswer: 'be taught',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 48
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'I ___ see the art installation yesterday.',
    options: [
      "isn't able to",
      "wasn't able to",
      'not able to',
      "won't be able to",
    ],
    correctAnswer: "wasn't able to",
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 49
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'We ___ to meet the novelist in the library.',
    options: ['not allowed', "don't allow", "aren't allowed", 'not allow'],
    correctAnswer: "aren't allowed",
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 50
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'Can you tell me when ___, please?',
    options: [
      'the parade starts',
      'does the parade start',
      'does the parade starts',
      'the parade does start',
    ],
    correctAnswer: 'the parade starts',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 51
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'We always watch ___ fiction films at the cinema',
    options: ['action', 'science', 'fantasy', 'animated'],
    correctAnswer: 'science',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 52
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText:
      'Shopping for clothes makes me feel ___. I usually go to bed early.',
    options: ['interested', 'annoyed', 'frightened', 'tired'],
    correctAnswer: 'tired',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 53
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText:
      "A: I'm making an app at the moment.\nB: No ___! That's great!",
    options: ['good', 'you', 'way', 'shame'],
    correctAnswer: 'way',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 54
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: "Do you ___ the cat's fur every evening?",
    options: ['brush', 'put', 'feed', 'take'],
    correctAnswer: 'brush',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 55
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText:
      "Oh no, the computer screen is ___. I can't do anything with it.",
    options: ['died', 'working', 'slow', 'frozen'],
    correctAnswer: 'frozen',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 56
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'You need to ___ the laptop off and on again.',
    options: ['press', 'switch', 'call', 'try'],
    correctAnswer: 'switch',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 57
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'Can you take this letter to the post ___, please?',
    options: ['centre', 'station', 'office', 'gallery'],
    correctAnswer: 'office',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 58
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'Craig ___ his finger with a sharp knife!',
    options: ['cut', 'burned', 'hit', 'broke'],
    correctAnswer: 'cut',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 59
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: "Let's get something to eat in the food ___.",
    options: ['store', 'park', 'court', 'trolley'],
    correctAnswer: 'court',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 60
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'A Master of Science is a type of university ___.',
    options: ['diploma', 'degree', 'model', 'job'],
    correctAnswer: 'degree',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 61
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'I ___ work in an office when I leave school.',
    options: [
      'probably might',
      'might probably',
      "won't probably",
      "probably won't",
    ],
    correctAnswer: "probably won't",
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 62
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: "Don't give ___, I know you can do it!",
    options: ['up', 'on', 'back', 'across'],
    correctAnswer: 'up',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 63
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: "You'll need to wear a ___ because the water's very cold.",
    options: ['kayak', 'paddle', 'wetsuit', 'helmet'],
    correctAnswer: 'wetsuit',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 64
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'How often do you ___ on social media?',
    options: ['follow', 'post', 'take', 'add'],
    correctAnswer: 'post',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 65
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'Malia always chats with her friends ___ the evening.',
    options: ['in', 'at', 'on', 'about'],
    correctAnswer: 'in',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 66
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'Do you know how to ___ a fire?',
    options: ['look for', 'watch', 'make', 'do'],
    correctAnswer: 'make',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 67
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText:
      "There's a big ___ here and lots of bats and other animals live in it",
    options: ['waterfall', 'sunset', 'path', 'cave'],
    correctAnswer: 'cave',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 68
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: "What's going ___? Why are the flowers on the ground?",
    options: ['off', 'on', 'out', 'in'],
    correctAnswer: 'on',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 69
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'This chilli and garlic ___ is amazing!',
    options: ['sauce', 'ingredient', 'fresh', 'raw'],
    correctAnswer: 'sauce',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 70
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'Eating ___ salads is good for you.',
    options: ['juicy', 'creamy', 'healthy', 'salty'],
    correctAnswer: 'healthy',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 71
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'This salmon goes well ___ lemon and boiled potatoes.',
    options: ['for', 'to', 'of', 'with'],
    correctAnswer: 'with',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 72
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText:
      "A: Are you ready to ___?\nB: Yes, I'd like sausages and chips.",
    options: ['sit', 'order', 'eat', 'request'],
    correctAnswer: 'order',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 73
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'Burcu wants to be an ___ one day.',
    options: ['actor', 'act', 'acting', 'action'],
    correctAnswer: 'actor',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 74
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'Do you ever sing ___ to songs on the radio in the car?',
    options: ['about', 'around', 'along', 'across'],
    correctAnswer: 'along',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 75
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText:
      "Adele is still putting on her football kit in the ___, but she'll be out soon.",
    options: ['tennis court', 'running track', 'rugby pitch', 'changing room'],
    correctAnswer: 'changing room',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 76
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'Would you like to ___ part in the race next month?',
    options: ['beat', 'take', 'record', 'volunteer'],
    correctAnswer: 'take',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 77
  // Source document repeats option label "b"; seeded as "d" for the fourth option.
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'What are you up ___ on Sunday?',
    options: ['to', 'for', 'in', 'about'],
    correctAnswer: 'to',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 78
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: "They're going to ___ on a really nice campsite on holiday.",
    options: ['eat', 'travel', 'stay', 'get'],
    correctAnswer: 'stay',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 79
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText:
      'We have to check ___ at 11 am tomorrow when we leave the hotel.',
    options: ['around', 'up', 'in', 'out'],
    correctAnswer: 'out',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 80
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'Air ___ makes it easy to visit places far away.',
    options: ['trip', 'travel', 'voyage', 'journey'],
    correctAnswer: 'travel',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 81
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: "Sorry, I didn't ___ that. Can you say it again?",
    options: ['catch', 'throw', 'speak', 'receive'],
    correctAnswer: 'catch',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 82
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: "The son of your dad's second wife is your ___.",
    options: ['half-brother', 'half-sister', 'stepsister', 'stepbrother'],
    correctAnswer: 'stepbrother',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 83
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'How did you ___ to know Rich? Was it at a club or sport?',
    options: ['see', 'go', 'have', 'get'],
    correctAnswer: 'get',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 84
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'The crime of stealing from shops is ___.',
    options: ['pickpocketing', 'shoplifting', 'burglary', 'vandalism'],
    correctAnswer: 'shoplifting',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 85
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'Police are ___ the area for the criminal at the moment.',
    options: ['interviewing', 'taking', 'searching', 'arresting'],
    correctAnswer: 'searching',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 86
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'In ___ lessons, we get to play different instruments.',
    options: ['Music', 'Art', 'PE', 'Literature'],
    correctAnswer: 'Music',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 87
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: "Calm ___, it's only a small test. You don't need to worry.",
    options: ['in', 'over', 'up', 'down'],
    correctAnswer: 'down',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 88
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'What do you ___ of this subject?',
    options: ['stay', 'think', 'feel', 'go'],
    correctAnswer: 'think',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 89
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: "You don't need to win, just ___ your best.",
    options: ['get', 'make', 'do', 'take'],
    correctAnswer: 'do',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 90
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'We must reduce the amount of carbon ___ in the atmosphere.',
    options: ['dioxide', 'energy', 'change', 'source'],
    correctAnswer: 'dioxide',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 91
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText:
      "Maybe you're ___, but I don't think it's a good idea overall.",
    options: ['true', 'OK', 'sure', 'right'],
    correctAnswer: 'right',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 92
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'Elanie has ___ nails.',
    options: ['pierced', 'painted', 'slim', 'well-built'],
    correctAnswer: 'painted',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 93
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: "My mum's a flight ___ so she travels a lot.",
    options: ['attendant', 'designer', 'trainer', 'agent'],
    correctAnswer: 'attendant',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 94
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'There are millions of stars in our ___.',
    options: ['planet', 'moon', 'galaxy', 'gravity'],
    correctAnswer: 'galaxy',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 95
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText:
      'Rosa is losing her hearing and may become ___ in the future.',
    options: ['ill', 'blind', 'allergic', 'deaf'],
    correctAnswer: 'deaf',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 96
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'My feet hurt. What do you think ___ do?',
    options: ['you should', 'I should', 'I could', 'I ought'],
    correctAnswer: 'I should',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 97
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: "What's the ___ of good communication?",
    options: ['definition', 'explanation', 'discussion', 'suggestion'],
    correctAnswer: 'definition',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 98
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText:
      "I've nearly finished this book, just two more ___ left to read.",
    options: ['plots', 'titles', 'chapters', 'covers'],
    correctAnswer: 'chapters',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 99
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText:
      'As far as I can ___, her art is very popular with teenagers.',
    options: ['hear', 'look', 'watch', 'see'],
    correctAnswer: 'see',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 100
  {
    testId: TEST_ID_A,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: "It's your birthday, so blow ___ the candles on the cake!",
    options: ['up', 'out', 'off', 'in'],
    correctAnswer: 'out',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
];

export const questionsB = [
  // 1
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'Aaron ___ watch science-fiction films very often.',
    options: ["don't", "aren't", "doesn't", "isn't"],
    correctAnswer: "doesn't",
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 2
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'A: ___ like hip hop?\nB: Yes, they do.',
    options: ['Do we', 'Does we', 'Does they', 'Do they'],
    correctAnswer: 'Do they',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 3
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'I ___ my school uniform today.',
    options: ["'s wearing", "'m wearing", 'wear', 'wears'],
    correctAnswer: "'m wearing",
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 4
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: '___ the cows in the field yesterday?',
    options: ['Is', 'Are', 'Were', 'Was'],
    correctAnswer: 'Were',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 5
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'We ___ write letters, but now we send emails.',
    options: ['used', 'used to', 'use to', 'use'],
    correctAnswer: 'used to',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 6
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: "Don't forget ___ your USB cable with you.",
    options: ['to take', 'take', 'taking', 'to taking'],
    correctAnswer: 'to take',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 7
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'This is the flat ___ we live.',
    options: ['who', 'which', 'that', 'where'],
    correctAnswer: 'where',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 8
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: '___ to take out the rubbish?',
    options: ['Must I', 'Can I', 'Do I have', 'Have I'],
    correctAnswer: 'Do I have',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 9
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'The shopping centre is ___ than my local shop.',
    options: ['biggest', 'bigger', 'as big', 'big'],
    correctAnswer: 'bigger',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 10
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: '___ common in schools in the future?',
    options: ['Will robots be', 'Do robots be', 'Robots will be', 'Be robot'],
    correctAnswer: 'Will robots be',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 11
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'You ___ bad if you cheat in the test.',
    options: ["won't feel", 'feel', 'will feel', 'are feeling'],
    correctAnswer: 'will feel',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 12
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'My cousins ___ swum with dolphins.',
    options: ['will', 'has', 'do', 'have'],
    correctAnswer: 'have',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 13
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'Stefan ___ pictures to social media. He hates it.',
    options: [
      'is never uploading',
      'never uploads',
      'are never uploading',
      'never upload',
    ],
    correctAnswer: 'never uploads',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 14
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: "I'm really looking forward ___ with Carla after school.",
    options: ['to chat', 'chat', 'to chatting', 'chatting'],
    correctAnswer: 'to chatting',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 15
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'Do you need ___ your mum first?',
    options: ['to message', 'messaging', 'to messaging', 'message'],
    correctAnswer: 'to message',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 16
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: "We didn't ___ any lightning last night.",
    options: ['seen', 'saw', 'seeing', 'see'],
    correctAnswer: 'see',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 17
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'We ___ TV when we suddenly heard the thunder.',
    options: ['were watching', 'watched', 'are watching', 'was watching'],
    correctAnswer: 'were watching',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 18
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: "I've ___ had sweet potatoes for lunch, so I'm not hungry.",
    options: ['never', 'ever', 'already', 'yet'],
    correctAnswer: 'already',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 19
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: "I haven't eaten peaches ___ I was a child.",
    options: ['for', 'yet', 'already', 'since'],
    correctAnswer: 'since',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 20
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'Liberty ___ salmon in her life.',
    options: [
      'never cook',
      'has never cooked',
      'have never cooked',
      "didn't cook",
    ],
    correctAnswer: 'has never cooked',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 21
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: "The cinema isn't big ___ for everybody to watch the film.",
    options: ['enough', 'too', 'more', 'the most'],
    correctAnswer: 'enough',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 22
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: "Musicals aren't as ___ action films, I think.",
    options: ['exciting than', 'more exciting', 'exciting', 'exciting as'],
    correctAnswer: 'exciting as',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 23
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: "We don't have ___ time to make our film.",
    options: ['many', 'some', 'much', 'lot of'],
    correctAnswer: 'much',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 24
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'You only need ___ lessons to sign this song really well.',
    options: ['a few', 'lots', 'a little', 'much'],
    correctAnswer: 'a few',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 25
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'Which team ___ the match tomorrow, do you think?',
    options: ['going to', 'will win', 'wins', 'are winning'],
    correctAnswer: 'will win',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 26
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: "We won't play tennis tomorrow unless the weather ___ nice.",
    options: ['will be', "won't be", 'is', "isn't"],
    correctAnswer: 'is',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 27
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: "We ___ take our sleeping bags, because it's cold at night.",
    options: ['should', 'ought', 'have', "don't have to"],
    correctAnswer: 'should',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 28
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: "You ___ take your passport if you're not going abroad.",
    options: ['ought to', "mustn't", "shouldn't", "don't have to"],
    correctAnswer: "don't have to",
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 29
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText:
      "This ___ be Esme's bag - it's red and it's got her name on it!",
    options: ['could', 'must', "can't", 'may'],
    correctAnswer: 'must',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 30
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: "If my family __ more money, we'd move away from here.",
    options: ['had', 'have', 'had have', 'will have'],
    correctAnswer: 'had',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 31
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'I ___ your parents for help if I were you.',
    options: ['will ask', 'ask', 'would ask', 'have asked'],
    correctAnswer: 'would ask',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 32
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'Ben, ___ is my uncle, is forty-two years old.',
    options: ['that', 'who', 'where', 'which'],
    correctAnswer: 'who',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 33
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'Hundreds of crimes ___ in the city every day.',
    options: ['commit', 'is committed', 'committed', 'are committed'],
    correctAnswer: 'are committed',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 34
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'The shoplifters ___ by the security camera last week.',
    options: ['were filmed', 'was filmed', 'are filmed', 'filmed'],
    correctAnswer: 'were filmed',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 35
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'My brother ___ from the city centre last week.',
    options: [
      'his bike got stolen',
      'stolen his bike got',
      'his stolen bike',
      'got his bike stolen',
    ],
    correctAnswer: 'got his bike stolen',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 36
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'Jamie said he ___ a practical exam.',
    options: ['has done', 'do', 'was doing', 'does'],
    correctAnswer: 'was doing',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 37
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'A: Who ___ you after school yesterday?\nB: Dylan and Kate.',
    options: ['did meet', 'met', 'meets', 'you met'],
    correctAnswer: 'met',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 38
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'When we arrived at the zoo, the animals ___ gone to sleep.',
    options: ['already had', 'was already', 'has already', 'had already'],
    correctAnswer: 'had already',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 39
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'Last month our school ___ a class election.',
    options: ['held', 'used to hold', 'hold', 'use to hold'],
    correctAnswer: 'held',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 40
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: '___ has Ciara been designing her own clothes?',
    options: ['How long', 'How many', 'How often', 'How old'],
    correctAnswer: 'How long',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 41
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: '___ ten art videos since this morning!',
    options: [
      "I haven't been watching",
      "I've watched",
      "I'm watching",
      "I've been watched",
    ],
    correctAnswer: "I've watched",
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 42
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: "This time next week, I'll ___ some voluntary work.",
    options: ['doing', 'do', 'be do', 'be doing'],
    correctAnswer: 'be doing',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 43
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'When they ___ their training, astronauts can go into space.',
    options: ['will pass', 'passed', 'pass', 'would pass'],
    correctAnswer: 'pass',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 44
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText:
      "If the astronauts hadn't seen the satellite in time, they ___ it!",
    options: [
      'would have hit',
      "wouldn't have hit",
      'would hit',
      "wouldn't hit",
    ],
    correctAnswer: 'would have hit',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 45
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'My mum asked me if ___ the doctor.',
    options: [
      'did I want to see',
      'I wanted to see',
      'I did want to see',
      'I was wanting to see',
    ],
    correctAnswer: 'I wanted to see',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 46
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'The nurse asked me ___ my leg.',
    options: ['to move not', "don't move", 'not move', 'not to move'],
    correctAnswer: 'not to move',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 47
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'The story will ___ next week.',
    options: ['publish', 'published', 'be published', 'is published'],
    correctAnswer: 'be published',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 48
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'I ___ finish this novel before the weekend.',
    options: [
      "won't be able to",
      "wasn't able to",
      "isn't able to",
      'not able to',
    ],
    correctAnswer: "won't be able to",
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 49
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: '___ to go to the abstract art show?',
    options: [
      'Do you allow',
      'Are you allowed',
      'Are you allow',
      "You're allowed",
    ],
    correctAnswer: 'Are you allowed',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 50
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: "I'd like to know where ___, please.",
    options: [
      'does the ceremony',
      'the ceremony does',
      'is the ceremony',
      'the ceremony is',
    ],
    correctAnswer: 'the ceremony is',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Grammar',
    isActive: true,
  },
  // 51
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'My parents love ___ to rock music, but I hate it.',
    options: ['listening', 'playing', 'watching', 'acting'],
    correctAnswer: 'listening',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 52
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: "They're ___ shoes. They're unusual and I like them.",
    options: ['frightening', 'annoying', 'interesting', 'tiring'],
    correctAnswer: 'interesting',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 53
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: "A: I don't feel well.\nB: ___ you!",
    options: ['Well', 'Poor', 'Good', 'No'],
    correctAnswer: 'Poor',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 54
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'Please ___ the cat. She looks hungry.',
    options: ['brush', 'spend', 'feed', 'put'],
    correctAnswer: 'feed',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 55
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: "The computer isn't ___. It isn't switching on.",
    options: ['working', 'crashing', 'dying', 'freezing'],
    correctAnswer: 'working',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 56
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText:
      'You need to ___ Control+C on your keyboard to copy information.',
    options: ['search', 'call', 'switch', 'press'],
    correctAnswer: 'press',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 57
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText:
      'We can find out about interesting things to do at the tourist information ___.',
    options: ['station', 'centre', 'gallery', 'hall'],
    correctAnswer: 'centre',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 58
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'Josie ___ her hand on that hot pan.',
    options: ['broke', 'cut', 'burned', 'hit'],
    correctAnswer: 'burned',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 59
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: "Let's see what's on at the multi-screen ___.",
    options: ['cinema', 'court', 'park', 'store'],
    correctAnswer: 'cinema',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 60
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'My aunt is my role ___, I learn a lot from her.',
    options: ['diploma', 'entrepreneur', 'boss', 'model'],
    correctAnswer: 'model',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 61
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'I ___ pass the test. I did lots of studying last week.',
    options: [
      'definitely will',
      'will definitely',
      'might definitely',
      'definitely might',
    ],
    correctAnswer: 'will definitely',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 62
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'Chantelle took ___ skiing when she was on holiday.',
    options: ['across', 'on', 'up', 'back'],
    correctAnswer: 'up',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 63
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'Make sure you wear ___ to protect your hands.',
    options: ['gloves', 'boots', 'a helmet', 'a life jacket'],
    correctAnswer: 'gloves',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 64
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'Do you like ___ selfies with people?',
    options: ['following', 'chatting', 'updating', 'taking'],
    correctAnswer: 'taking',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 65
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'Marco always gets up early ___ a school day.',
    options: ['at', 'on', 'about', 'in'],
    correctAnswer: 'on',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 66
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'Do you know how to ___ a shelter?',
    options: ['discover', 'make', 'listen', 'sleep'],
    correctAnswer: 'make',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 67
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: "Aagh! there's a huge ___ in my tent!",
    options: ['star', 'waterfall', 'spider', 'cave'],
    correctAnswer: 'spider',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 68
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: "I'm sorry, I didn't ___ to do that. It was an accident.",
    options: ['explain', 'realise', 'mean', 'go'],
    correctAnswer: 'mean',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 69
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: "You should never eat ___ chicken, it's very dangerous.",
    options: ['cooked', 'fried', 'fresh', 'raw'],
    correctAnswer: 'raw',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 70
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'I love a ___ salad with lots of seeds and peppers in.',
    options: ['creamy', 'crunchy', 'fatty', 'buttery'],
    correctAnswer: 'crunchy',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 71
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: "Pizza every day isn't good ___ you.",
    options: ['for', 'to', 'with', 'of'],
    correctAnswer: 'for',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 72
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: "Take a ___ and I'll get you the menu.",
    options: ['window', 'table', 'seat', 'chair'],
    correctAnswer: 'seat',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 73
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: "___ of the film all agree that it's brilliant.",
    options: ['Performers', 'Entertainers', 'Actors', 'Reviewers'],
    correctAnswer: 'Reviewers',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 74
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText:
      'I sometimes ___ tracks of me playing the guitar and singing.',
    options: ['lip-synch', 'record', 'write', 'go'],
    correctAnswer: 'record',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 75
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText:
      "How many points have they got? I can't see the ___ from here.",
    options: ['scoreboard', 'changing room', 'tournament', 'fan'],
    correctAnswer: 'scoreboard',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 76
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: "He's ___ the world record of fifty-six seconds!",
    options: ['scored', 'supported', 'broken', 'won'],
    correctAnswer: 'broken',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 77
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'What are you ___ to today?',
    options: ['about', 'across', 'down', 'up'],
    correctAnswer: 'up',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 78
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'How often do you ___ abroad?',
    options: ['get', 'go', 'have', 'rent'],
    correctAnswer: 'go',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 79
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'We had a lovely ___ from the 15th floor of the hotel.',
    options: ['view', 'guest', 'reception', 'pool'],
    correctAnswer: 'view',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 80
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText:
      'On holiday we went on a(n) ___ one morning to an old castle.',
    options: ['travel', 'voyage', 'excursion', 'journey'],
    correctAnswer: 'excursion',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 81
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: "Sorry, I didn't ___ the first part. Can you say it again?",
    options: ['speak', 'listen', 'go', 'get'],
    correctAnswer: 'get',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 82
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: "The daughter of your dad's second wife is your ___.",
    options: ['half-brother', 'half-sister', 'stepsister', 'stepbrother'],
    correctAnswer: 'stepsister',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 83
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'Bea and I have the same sense of ___. We laugh together.',
    options: ['humour', 'common', 'time', 'argument'],
    correctAnswer: 'humour',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 84
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText:
      "The crime of taking something from someone else's house is called ___.",
    options: ['vandalism', 'shoplifting', 'pickpocketing', 'burglary'],
    correctAnswer: 'burglary',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 85
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText:
      'One job that the police do after a crime is ___ any witnesses who saw it.',
    options: ['search', 'interview', 'take', 'arrest'],
    correctAnswer: 'interview',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 86
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'In our ___ lesson yesterday, we made a salad.',
    options: ['Physics', 'PE', 'Cooking', 'Literature'],
    correctAnswer: 'Cooking',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 87
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'Can you hand ___ these forms to everyone for me, please?',
    options: ['out', 'in', 'down', 'to'],
    correctAnswer: 'out',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 88
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'How long are you staying ___?',
    options: ['to', 'in', 'for', 'at'],
    correctAnswer: 'for',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 89
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText:
      'Carla decided to ___ the most of her new school and explore.',
    options: ['get', 'take', 'do', 'make'],
    correctAnswer: 'make',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 90
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'Wind power is a good example of renewable ___.',
    options: ['source', 'energy', 'warming', 'centre'],
    correctAnswer: 'energy',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 91
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText:
      "A: One thousand people signed our petition. That's brilliant!\nB: You can ___ that again!",
    options: ['say', 'think', 'agree', 'suppose'],
    correctAnswer: 'say',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 92
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: "Zach's ___ because he goes to the gym every day.",
    options: ['well-built', 'average-height', 'curly', 'painted'],
    correctAnswer: 'well-built',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 93
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: "My dad's a computer ___ and he makes apps.",
    options: ['critic', 'trainer', 'attendant', 'programmer'],
    correctAnswer: 'programmer',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 94
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: "I wonder what it's like to live on a ___.",
    options: ['satellite', 'comet', 'telescope', 'space station'],
    correctAnswer: 'space station',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 95
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: "I've got an ear ___ and it's really painful!",
    options: ['depression', 'infection', 'blindness', 'operation'],
    correctAnswer: 'infection',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 96
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: '___ keep your foot up until the doctor sees you.',
    options: ['I should', 'You need', "You'd better", 'You ought'],
    correctAnswer: "You'd better",
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 97
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'How do you ___ this word?',
    options: ['inform', 'suggest', 'communicate', 'pronounce'],
    correctAnswer: 'pronounce',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 98
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: "A ___ is a book about someone's life.",
    options: ['chapter', 'biography', 'novel', 'plot'],
    correctAnswer: 'biography',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 99
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: "___ far as I'm concerned, that book is awful.",
    options: ['Is', 'As', 'For', 'In'],
    correctAnswer: 'As',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
  // 100
  {
    testId: TEST_ID_B,
    type: 'MCQ',
    inputType: 'OPTIONS',
    questionText: 'Can you help me put ___ the decorations for the party?',
    options: ['in', 'on', 'up', 'out'],
    correctAnswer: 'up',
    explanation: null,
    points: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    isActive: true,
  },
];

export const allQuestions = [...questionsA, ...questionsB];

export default allQuestions;
