name: Backend Deploy (CI/CD)

on:
  push:
    branches:
      - main # Yoki o'zingizning asosiy branch nomingiz (masalan, master)
    paths:
      - 'backend/**' # Faqat backend papkasida o'zgarish bo'lganda ishlaydi

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }} # Yoki kalit (SSH Key) ishlatsangiz: key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT || 22 }}
          script: |
            # 1. Loyiha papkasiga kirish (O'zingizning serveringizdagi manzilni ko'rsatasiz)
            cd /root/mk_academia/

            # 2. Yangi kodni Git dan tortib olish
            git pull origin main

            # 3. Backend papkasiga kirib qolgan fayllarning Docker-ni qayta build qilish
            cd backend
            docker compose down
            docker compose up --build -d

            # 4. Keraksiz/Eski image'larni tozalash (joyni tejash uchun)
            docker image prune -f
